#!/usr/bin/env python3
"""Generate source-backed M5.1 CLI, schema, and diagnostic reference pages."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs" / "user"
CONTRACT_PATH = ROOT / "testdata" / "M5_CLI_CONTRACT.v1.json"
GENERATED_NOTICE = "<!-- Generated by tools/generate_m5_1_reference.py; do not edit. -->"

PRODUCT_SCHEMAS = (
    "M5_CONFIG.schema.json",
    "M5_PROJECT_INDEX.schema.json",
    "M5_DATA_PLAN.schema.json",
    "M5_CLI_OUTPUT.schema.json",
    "M5_CLI_STREAM_ITEM.schema.json",
    "M5_JOB_RECORD.schema.json",
    "M5_JOB_EVENT.schema.json",
    "M5_PRUNE_PLAN.schema.json",
    "M5_RESULT_INSPECTION.schema.json",
    "M5_TRAJECTORY_RECORD.schema.json",
    "M5_TRAJECTORY_STREAM.schema.json",
    "M4_RUN_MANIFEST.schema.json",
    "M4_PROVENANCE_BUNDLE.schema.json",
    "M5_BUILD_MANIFEST.schema.json",
)

EXAMPLES = {
    "M5_CONFIG.schema.json": "M5_CONFIG.example.toml",
    "M5_PROJECT_INDEX.schema.json": "M5_PROJECT_INDEX.example.yaml",
    "M5_DATA_PLAN.schema.json": "M5_DATA_PLAN.example.json",
    "M5_CLI_OUTPUT.schema.json": "M5_CLI_OUTPUT.example.json",
    "M5_CLI_STREAM_ITEM.schema.json": "M5_CLI_STREAM_ITEM.example.json",
    "M5_JOB_RECORD.schema.json": "M5_JOB_RECORD.example.json",
    "M5_JOB_EVENT.schema.json": "M5_JOB_EVENT.example.json",
    "M5_PRUNE_PLAN.schema.json": "M5_PRUNE_PLAN.example.json",
    "M5_RESULT_INSPECTION.schema.json": "M5_RESULT_INSPECTION.example.json",
    "M5_TRAJECTORY_RECORD.schema.json": "M5_TRAJECTORY_RECORD.example.json",
    "M5_TRAJECTORY_STREAM.schema.json": "M5_TRAJECTORY_STREAM.example.json",
    "M5_BUILD_MANIFEST.schema.json": "M5_BUILD_MANIFEST.example.json",
}

SCHEMA_ZH_TITLES = {
    "M5_CONFIG.schema.json": "Trajecta 本机配置",
    "M5_PROJECT_INDEX.schema.json": "Trajecta 项目编排索引",
    "M5_DATA_PLAN.schema.json": "Trajecta 可重复生成的资料计划",
    "M5_CLI_OUTPUT.schema.json": "Trajecta CLI 单次 JSON 响应",
    "M5_CLI_STREAM_ITEM.schema.json": "Trajecta JSONL 流记录",
    "M5_JOB_RECORD.schema.json": "Trajecta 持久化任务轮次记录",
    "M5_JOB_EVENT.schema.json": "Trajecta 持久化任务事件",
    "M5_PRUNE_PLAN.schema.json": "Trajecta 存储清理预览计划",
    "M5_RESULT_INSPECTION.schema.json": "Trajecta 结果检查摘要",
    "M5_TRAJECTORY_RECORD.schema.json": "Trajecta 轨迹记录",
    "M5_TRAJECTORY_STREAM.schema.json": "Trajecta 轨迹流首记录",
    "M4_RUN_MANIFEST.schema.json": "Trajecta 运行清单",
    "M4_PROVENANCE_BUNDLE.schema.json": "Trajecta 粒子状态溯源信息",
    "M5_BUILD_MANIFEST.schema.json": "Trajecta 软件包构建清单",
}

DIAGNOSTIC_PREFIXES = {
    "case",
    "cli",
    "command",
    "config",
    "daemon",
    "data",
    "doctor",
    "job",
    "job_backend",
    "manifest",
    "met",
    "project",
    "report",
    "result",
    "run",
    "scheduler",
    "worker",
}
CODE_PATTERN = re.compile(r'"([a-z][a-z0-9_-]*(?:\.[a-z][a-z0-9_-]*)+)"')
NON_DIAGNOSTIC_CODES = {"config.toml"}

COMMAND_PURPOSES = {
    "config init": ("Create a machine configuration at the selected path", "在所选路径创建本机配置"),
    "config path": ("Print the selected machine-configuration path", "显示当前本机配置路径"),
    "config list": ("List every configuration leaf and its value", "列出所有最末级配置字段及其值"),
    "config get": ("Read one configuration selector", "读取一个配置选择器"),
    "config set": ("Validate and atomically update one selector", "校验并原子更新一个配置选择器"),
    "config unset": ("Remove an optional selector", "移除一个可选配置选择器"),
    "config validate": ("Validate the complete selected configuration", "校验完整的所选配置"),
    "project init": ("Create a project index and initial directory layout", "创建项目索引和初始目录结构"),
    "project status": ("Report draft, configured, or finalized project state", "显示项目的草稿、已配置或已定稿状态"),
    "project show": ("Show the resolved project index and document summary", "显示解析后的项目索引与文档摘要"),
    "project get": ("Read one project selector", "读取一个项目选择器"),
    "project set": ("Validate and update one project selector", "校验并更新一个项目选择器"),
    "project unset": ("Remove an optional project selector", "移除一个可选项目选择器"),
    "project validate": ("Validate the index and referenced Case and Profile documents", "校验项目索引及其引用的案例与运行配置"),
    "project data-plan": ("Calculate deterministic dataset requirements and local status", "计算可重复生成的资料需求及其本地状态"),
    "project finalize": ("Inspect prepared data and atomically bind DatasetLocks", "检查已准备资料，并以原子更新方式绑定资料锁"),
    "case validate": ("Validate a Case for a selected intent", "按指定用途校验案例"),
    "case resolve": ("Expand a Case into its resolved public document", "将案例展开为解析后的公开文档"),
    "data inspect": ("Inspect one supported meteorological file", "检查一个受支持的气象资料文件"),
    "data lock": ("Build a DatasetLock from a Case, profile, and data root", "根据案例、资料配置和资料根目录构建资料锁"),
    "met probe": ("Query selected meteorological points", "查询指定气象点"),
    "met replay": ("Replay a JSONL meteorological query stream", "重放 JSONL 气象查询流"),
    "doctor": ("Check configuration, project, data, filesystem, and optional deep probes", "检查配置、项目、资料和文件系统；按需执行深入检查"),
    "run": ("Submit a project Profile or direct Case/Profile pair", "提交项目运行配置，或直接提交案例与运行配置"),
    "job list": ("List the latest visible attempt for each job series", "列出各任务系列的最新可见执行轮次"),
    "job status": ("Read the current snapshot for one job series", "读取一个任务系列的当前快照"),
    "job wait": ("Wait for the current attempt to become terminal", "等待当前执行轮次进入终态"),
    "job events": ("Read or follow durable queue events", "读取或跟随持久化队列事件"),
    "job cancel": ("Request safe cancellation or force-stop the current attempt", "安全取消或强制停止当前执行轮次"),
    "job rerun": ("Create the next attempt in an existing series", "在现有任务系列中创建下一执行轮次"),
    "job forget": ("Hide a terminal series from routine list output", "从日常列表隐藏终态任务系列"),
    "job prune": ("Return the dry-run storage-prune plan", "返回只读存储清理计划"),
    "result inspect": ("Summarize a run manifest, artifacts, and available SQLite counts", "汇总运行清单、产物和可用 SQLite 数量"),
    "result verify": ("Run quick or full product verification", "执行快速或完整结果验证"),
    "result trajectory": ("Stream trajectory rows for selected or all particles", "流式读取指定粒子或全部粒子的轨迹记录"),
    "run report": ("Create or refresh RESULT/run-report.md", "创建或刷新 RESULT/run-report.md"),
}


def default_binary() -> Path:
    suffix = ".exe" if sys.platform == "win32" else ""
    return ROOT / "target" / "debug" / f"trajecta-cli{suffix}"


def binary_help(binary: Path) -> str:
    if not binary.is_file():
        raise RuntimeError(f"CLI binary does not exist: {binary}")
    completed = subprocess.run(
        [str(binary), "--help"],
        cwd=ROOT,
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if completed.returncode != 0 or completed.stderr:
        raise RuntimeError(
            f"CLI help failed with exit {completed.returncode}: "
            f"{completed.stderr.decode('utf-8', errors='replace')}"
        )
    return completed.stdout.decode("utf-8").replace("\r\n", "\n").rstrip()


def command_synopses(help_text: str) -> list[str]:
    try:
        block = help_text.split("Commands:\n", 1)[1].split("\n\nmet probe options:", 1)[0]
    except IndexError as error:
        raise RuntimeError("CLI help has no parseable Commands section") from error
    return [line.strip() for line in block.splitlines() if line.strip()]


def command_path(synopsis: str, known: set[str]) -> str:
    matches = [path for path in known if synopsis == path or synopsis.startswith(path + " ")]
    if not matches:
        raise RuntimeError(f"help synopsis has no command contract entry: {synopsis}")
    return max(matches, key=len)


def cli_pages(help_text: str) -> dict[Path, str]:
    contract = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))
    entries = {entry["path"]: entry for entry in contract["commands"]}
    entries["run report"] = {
        "path": "run report",
        "stage": "m5_a3",
        "owner": "b",
        "streaming": False,
    }
    synopses = command_synopses(help_text)
    paths = [command_path(synopsis, set(entries)) for synopsis in synopses]
    if len(paths) != len(set(paths)):
        raise RuntimeError("CLI help contains a duplicate command synopsis")
    if set(paths) != set(entries):
        missing = sorted(set(entries) - set(paths))
        extra = sorted(set(paths) - set(entries))
        raise RuntimeError(f"CLI help/contract drift: missing={missing}, extra={extra}")

    if set(COMMAND_PURPOSES) != set(entries):
        missing = sorted(set(entries) - set(COMMAND_PURPOSES))
        extra = sorted(set(COMMAND_PURPOSES) - set(entries))
        raise RuntimeError(f"CLI purpose drift: missing={missing}, extra={extra}")

    rows = []
    zh_rows = []
    for synopsis, path in zip(synopses, paths, strict=True):
        entry = entries[path]
        output = "JSONL capable" if entry["streaming"] else "single response"
        zh_output = "可使用 JSONL" if entry["streaming"] else "单次响应"
        rows.append(f"| `{synopsis}` | {COMMAND_PURPOSES[path][0]} | {output} |")
        zh_rows.append(f"| `{synopsis}` | {COMMAND_PURPOSES[path][1]} | {zh_output} |")
    en = f"""---
title: CLI command tree
description: Complete Trajecta 0.1.0-alpha.1 command synopsis generated from the real binary help and checked against the frozen CLI contract.
---

{GENERATED_NOTICE}

# CLI command tree

This page is generated from the `trajecta --help` output produced by the current
binary. Every command is cross-checked against
`testdata/M5_CLI_CONTRACT.v1.json`; the implemented `run report` command is
checked alongside that frozen contract.

## Command form

```text
trajecta [GLOBAL OPTIONS] COMMAND [ARGUMENTS]
```

Global options may appear before or after a command. `--config PATH` selects
the machine configuration and therefore the local daemon endpoint and job
catalog. `--project PATH` selects a project root or its index for project-aware
commands.

| Option | Meaning |
| --- | --- |
| `--format human` | Human-readable output; this is the default |
| `--format json` | One `trajecta.cli-output/v1` envelope |
| `--format jsonl` | One `trajecta.cli-stream-item/v1` object per line for a stream-capable command |
| `--json` | Alias for `--format json` |
| `--config PATH` | Explicit machine configuration, ahead of environment and platform defaults |
| `--project PATH` | Explicit project root or `trajecta-project.yaml` path |
| `-h`, `--help` | Display command help |

## Argument conventions

| Placeholder | Accepted value |
| --- | --- |
| `PATH`, `FILE`, `DIR` | Filesystem path; project document paths remain inside the project jail |
| `KEY`, `SELECTOR` | Dotted configuration or project selector |
| `JOB_ID` | Job-series identifier returned by run admission |
| `RESULT` | Job-series ID, run ID, or result-directory path accepted by result commands |
| `UNIX` | Integer UTC Unix timestamp in seconds |
| `JSONL` | Newline-delimited JSON file path; selected meteorology commands also accept `-` for standard input or output |

## Runtime behavior

- `run` waits in the foreground unless `--detach` is supplied. Detached mode
  returns after durable queue admission.
- A foreground run exits after the attempt becomes terminal. Use `job status`,
  `job wait`, or `job events` to reconnect from another terminal.
- `job events`, meteorological streams, and trajectory output can use JSONL.
  Their final stream item is a summary.
- `job prune` returns a dry-run plan in this alpha release. It has no delete or
  apply option.
- Application errors in machine mode use the same envelope shape as successful
  commands. Process exit codes remain available to shell scripts.

## Commands

| Synopsis | Purpose | Machine output |
| --- | --- | --- |
{chr(10).join(rows)}

The procedural guides provide complete sequences for
[project preparation](../how-to/progressive-configuration.md),
[queue operation](../how-to/run-queue.md), and
[result reading](../how-to/results.md).

## Exact binary help

```text
{help_text}
```
"""
    zh = f"""---
title: CLI 命令树
description: 根据真实二进制帮助生成 Trajecta 0.1.0-alpha.1 的完整命令概要，并与 CLI 结构清单逐项核对。
---

{GENERATED_NOTICE}

# CLI 命令树

本页根据当前二进制的 `trajecta --help` 输出生成。全部命令都会与
`testdata/M5_CLI_CONTRACT.v1.json` 逐项核对；`run report` 也纳入同一检查。

## 命令形式

```text
trajecta [GLOBAL OPTIONS] COMMAND [ARGUMENTS]
```

全局参数可以位于命令前后。`--config PATH` 选择本机配置，进而确定本地守护进程端点和任务
数据库。`--project PATH` 为需要项目的命令选择项目根目录或项目索引。

| 参数 | 含义 |
| --- | --- |
| `--format human` | 人类可读输出，也是默认格式 |
| `--format json` | 输出一个 `trajecta.cli-output/v1` JSON 响应对象 |
| `--format jsonl` | 支持流式输出的命令每行写一个 `trajecta.cli-stream-item/v1` 对象 |
| `--json` | `--format json` 的别名 |
| `--config PATH` | 显式指定本机配置，优先于环境变量和平台默认路径 |
| `--project PATH` | 显式指定项目根目录或 `trajecta-project.yaml` |
| `-h`、`--help` | 显示命令帮助 |

## 参数名称

| 占位符 | 接受的值 |
| --- | --- |
| `PATH`、`FILE`、`DIR` | 文件系统路径；项目文档路径必须留在项目根目录内 |
| `KEY`、`SELECTOR` | 点分配置选择器或项目选择器 |
| `JOB_ID` | 任务准入返回的任务系列 ID |
| `RESULT` | 结果命令接受的任务系列 ID、运行 ID 或结果目录路径 |
| `UNIX` | 以秒表示的 UTC Unix 时间戳整数 |
| `JSONL` | 每行一个 JSON 对象的文件路径；部分气象命令还接受 `-` 作为标准输入或输出 |

## 运行行为

- `run` 默认在前台等待；`--detach` 在任务持久化接收后返回。
- 前台运行会等待执行轮次进入终态。另一个终端可通过 `job status`、`job wait` 或
  `job events` 重新连接。
- `job events`、气象数据流和轨迹输出可以使用 JSONL，最后一项为汇总。
- 当前 Alpha 版本的 `job prune` 只返回预览计划，不提供删除或应用参数。
- 机器可读模式中的应用错误与成功命令使用相同响应格式，Shell 脚本仍可读取进程退出码。

## 命令

| 命令概要 | 用途 | 机器输出 |
| --- | --- | --- |
{chr(10).join(zh_rows)}

完整操作顺序见[项目准备](../how-to/progressive-configuration.md)、
[队列运行](../how-to/run-queue.md)与[结果读取](../how-to/results.md)。

## 二进制原始帮助

```text
{help_text}
```
"""
    return {
        DOCS / "en" / "reference" / "cli.md": en,
        DOCS / "zh-CN" / "reference" / "cli.md": zh,
    }


def schema_rows(locale: str) -> list[str]:
    rows = []
    for name in PRODUCT_SCHEMAS:
        path = ROOT / "testdata" / name
        schema = json.loads(path.read_text(encoding="utf-8"))
        required = schema.get("required", [])
        required_text = ", ".join(f"`{item}`" for item in required) or "—"
        source = f"https://github.com/origin652/trajecta/blob/main/trajecta/testdata/{name}"
        example_name = EXAMPLES.get(name)
        if example_name:
            example_url = (
                "https://github.com/origin652/trajecta/blob/main/trajecta/testdata/"
                + example_name
            )
            example = f"[{example_name}]({example_url})"
        else:
            example = "—"
        title = (
            SCHEMA_ZH_TITLES[name]
            if locale == "zh-CN"
            else schema.get("title", name)
        )
        schema_link = f"[{name}]({source})"
        rows.append(f"| {title} | {schema_link} | {example} | {required_text} |")
    return rows


def schema_pages() -> dict[Path, str]:
    rows = "\n".join(schema_rows("en"))
    zh_rows = "\n".join(schema_rows("zh-CN"))
    en = f"""---
title: JSON and JSONL schemas
description: Source-backed schemas for Trajecta configuration, control-plane streams, results, manifests, provenance, and package metadata.
---

{GENERATED_NOTICE}

# JSON and JSONL schemas

Trajecta versions each machine-readable disk or stream format independently.
The `schema_version` inside a document selects that format contract; the
software version identifies the executable that reads or writes it. The current
release keeps the existing schema identifiers.

The linked schema files define required fields, value types, enumerations,
additional-property rules, and nested records. Examples show one valid instance
and are also used as validation fixtures. Case and RunProfile follow their
public YAML document contracts; see
[Project, Case, and Profile](documents.md).

## Schema families

| Family | Formats | Where they appear |
| --- | --- | --- |
| Configuration and project | Machine configuration, project index, data plan | Files edited during local and project setup |
| CLI response | Single JSON envelope and JSONL stream item | Standard output in machine mode |
| Job control | Job record, job event, prune plan | Local daemon queries and queue history |
| Result reading | Result inspection, trajectory record, trajectory stream | `result inspect` and `result trajectory` output |
| Scientific product | Run manifest and provenance bundle | Every completed result directory |
| Distribution | Build manifest | Release package root |

## Machine-output envelopes

`trajecta.cli-output/v1` represents one command response. It contains the full
command path, an `ok` flag, a command-specific `data` value, and structured
diagnostics. A usage error in JSON mode uses the same outer format while
retaining process exit code `2`.

`trajecta.cli-stream-item/v1` represents one JSONL line. Its `kind` selects a
data item, diagnostic, or final summary. The outer `sequence` orders lines in
that invocation. A job event inside `data` has its own durable global sequence
for reconnection.

## Documents on disk

The configuration and project-index schemas reject unknown properties and
invalid value types. Product commands validate them before an atomic update.
The data plan is generated from resolved project requirements and local status;
it can be written to a file and reviewed before data preparation.

The run manifest and provenance bundle are immutable result identities after a
successful closeout. Open them through `result inspect` and `result verify`
when possible, since those commands also check their relationship with SQLite
and the selected attempt.

## Schema index

| Product | Schema | Example | Required top-level fields |
| --- | --- | --- | --- |
{rows}

Schema versions identify disk and stream formats independently of the software
version. Automation can select a parser from `schema_version` before reading
command-specific fields. The [exit-code reference](exit-codes.md) explains how
schema-valid machine output relates to process status.
"""
    zh = f"""---
title: JSON 与 JSONL 格式规范
description: Trajecta 配置、任务控制、运行结果、清单、溯源信息和安装包元数据的格式规范。
---

{GENERATED_NOTICE}

# JSON 与 JSONL 格式规范

Trajecta 为每一种机器可读的磁盘格式和数据流格式单独编号。文档中的 `schema_version`
用于选择相应的格式规范，软件版本则用于识别读写该文档的程序版本。当前发行版沿用现有的
格式版本号。

下方链接指向仓库中的 JSON Schema 文件，其中规定了必填字段、值类型、枚举值、未知字段
处理方式以及嵌套记录的结构。每个示例都是一份可通过校验的完整文档，也会在测试中作为
校验样例使用。案例（`Case`）和运行配置（`RunProfile`）采用公开的 YAML 文档格式，详见
[项目、案例与运行配置](documents.md)。

## 格式分组

| 分组 | 包含的格式 | 出现位置 |
| --- | --- | --- |
| 配置与项目 | 本机配置、项目索引、资料计划 | 设置本机环境和准备项目时编辑或生成的文件 |
| CLI 响应 | 单次 JSON 响应、JSONL 流记录 | 机器可读模式下的标准输出 |
| 任务控制 | 任务记录、任务事件、清理预览计划 | 守护进程查询结果和持久化队列历史 |
| 结果读取 | 结果检查摘要、轨迹记录、轨迹流 | `result inspect` 与 `result trajectory` 的输出 |
| 运行结果 | 运行清单、溯源信息 | 每个已完成的结果目录 |
| 软件分发 | 构建清单 | 发布包根目录 |

## 机器可读输出格式

`trajecta.cli-output/v1` 表示一条命令的完整响应。它记录命令路径、`ok` 状态、该命令专用的
`data` 内容以及结构化诊断信息。JSON 模式下的用法错误也采用同一响应格式，同时保留进程
退出码 `2`。

`trajecta.cli-stream-item/v1` 表示 JSONL 数据流中的一行。`kind` 用于区分数据、诊断信息和
末尾汇总，`sequence` 表示各行在本次命令调用中的顺序。若 `data` 内装有任务事件，该事件
还带有自己的持久化全局序号，重新连接事件流时可从该序号继续读取。

## 磁盘文档

本机配置和项目索引会拒绝未知字段及类型错误。相关命令在原子更新文件前校验整份文档，
校验失败时保留原文件。资料计划根据解析后的项目需求和本地资料状态生成；可以先将其写入
文件，确认下载范围和目标路径后再准备资料。

一次运行正常收尾后，运行清单和溯源信息会与 SQLite 结果一起保存。日常查看时可优先使用
`result inspect` 和 `result verify`，两条命令会同时检查这些文件、SQLite 数据库及当前
执行轮次之间的对应关系。

## 格式索引

| 文档或记录 | Schema | 示例 | 顶层必填字段 |
| --- | --- | --- | --- |
{zh_rows}

结构版本独立标识磁盘格式或数据流格式，不随软件版本自动递增。自动化程序可以先读取
`schema_version`，选择对应的解析器，再处理各命令专用字段。[退出码参考](exit-codes.md)
说明机器可读输出与进程状态之间的对应关系。
"""
    return {
        DOCS / "en" / "reference" / "schemas.md": en,
        DOCS / "zh-CN" / "reference" / "schemas.md": zh,
    }


def diagnostic_sources() -> dict[str, set[str]]:
    roots = (
        ROOT / "crates" / "trajecta-cli" / "src",
        ROOT / "crates" / "trajecta-job" / "src",
    )
    found: dict[str, set[str]] = {}
    for source_root in roots:
        for path in sorted(source_root.rglob("*.rs")):
            relative = path.relative_to(ROOT).as_posix()
            text = path.read_text(encoding="utf-8")
            for code in CODE_PATTERN.findall(text):
                if (
                    code not in NON_DIAGNOSTIC_CODES
                    and code.split(".", 1)[0] in DIAGNOSTIC_PREFIXES
                ):
                    found.setdefault(code, set()).add(relative)
    return found


def diagnostics_pages() -> dict[Path, str]:
    found = diagnostic_sources()
    if not found:
        raise RuntimeError("no source-backed diagnostics found")
    groups: dict[str, list[tuple[str, set[str]]]] = {}
    for code, sources in sorted(found.items()):
        groups.setdefault(code.split(".", 1)[0], []).append((code, sources))

    sections = []
    for prefix, entries in groups.items():
        rows = []
        for code, sources in entries:
            links = []
            for source in sorted(sources):
                url = f"https://github.com/origin652/trajecta/blob/main/trajecta/{source}"
                links.append(f"[`{source}`]({url})")
            rows.append(f"| `{code}` | {', '.join(links)} |")
        sections.append(f"## `{prefix}.*`\n\n| Code | Source |\n| --- | --- |\n" + "\n".join(rows))
    body = "\n\n".join(sections)
    en = f"""---
title: Diagnostic codes
description: Source-backed index of stable Trajecta CLI, daemon, worker, job, project, data, and result diagnostic codes.
---

{GENERATED_NOTICE}

# Diagnostic codes

Machine output identifies a condition through `diagnostics[].code`. Codes are
short, stable selectors for scripts and troubleshooting; messages add the path,
value, operating-system error, or run identity relevant to one invocation.

## Diagnostic record

| Field | Content |
| --- | --- |
| `severity` | `error`, `warning`, or `info` |
| `code` | Namespaced condition such as `project.lock_missing` |
| `message` | Human-readable detail for this occurrence |
| `path` | Ordered field or array-index components locating a document value |
| `hint` | Optional next command or correction |

An envelope can contain several diagnostics. `project finalize`, for example,
can return one preflight failure with nested project or data conditions. Read
all entries before changing a document. In JSONL, a diagnostic is a stream item
with `kind: "diagnostic"`; a later summary closes the stream.

## Using codes in automation

Branch on the complete code and inspect the process exit status separately.
The message can gain more context between releases without changing the
condition selected by the code. Unknown codes are best retained in logs and
handled as the severity indicates, allowing a newer producer to communicate
with an older monitoring script.

The namespace usually identifies the component:

| Prefix | Area |
| --- | --- |
| `config.*`, `doctor.*` | Machine configuration and environment checks |
| `project.*`, `case.*`, `data.*` | Project documents, dataset planning, and locks |
| `daemon.*`, `job_backend.*`, `scheduler.*` | Local control plane, catalog, and admission |
| `job.*`, `worker.*`, `run.*` | Attempt lifecycle and numerical worker |
| `met.*` | Meteorological probe or replay command |
| `result.*`, `report.*` | Result inspection, verification, trajectory output, and report creation |

## Source index

The list below is rebuilt from production Rust string literals. Source links
are included for contributors who are tracing the branch that emitted a code.

Start troubleshooting by symptom in the [operations index](../operations/troubleshooting.md).

{body}
"""
    zh_sections = []
    for prefix, entries in groups.items():
        zh_group_rows = []
        for code, sources in entries:
            links = []
            for source in sorted(sources):
                url = f"https://github.com/origin652/trajecta/blob/main/trajecta/{source}"
                links.append(f"[`{source}`]({url})")
            zh_group_rows.append(f"| `{code}` | {', '.join(links)} |")
        zh_sections.append(
            f"## `{prefix}.*`\n\n| 诊断码 | 源码位置 |\n| --- | --- |\n"
            + "\n".join(zh_group_rows)
        )
    zh_body = "\n\n".join(zh_sections)

    zh = f"""---
title: 诊断码
description: 根据源码生成的 Trajecta CLI、守护进程、工作进程、任务、项目、资料和结果诊断码索引。
---

{GENERATED_NOTICE}

# 诊断码

机器可读输出通过 `diagnostics[].code` 标识具体问题。脚本和故障排查流程可以依赖完整诊断码
选择处理分支；`message` 则补充本次命令涉及的路径、字段值、操作系统错误或运行 ID。

## 诊断记录结构

| 字段 | 内容 |
| --- | --- |
| `severity` | `error`、`warning` 或 `info` |
| `code` | 带命名空间的诊断码，例如 `project.lock_missing` |
| `message` | 针对本次问题给出的可读说明 |
| `path` | 定位文档字段或数组元素的有序路径 |
| `hint` | 可选的修正建议或下一条命令 |

一条响应可以包含多项诊断信息。例如，`project finalize` 的预检可能同时发现项目文档和资料
准备问题。处理前应遍历 `diagnostics` 中的全部记录。JSONL 输出把每条诊断信息写成
`kind: "diagnostic"` 的独立记录，并在数据流末尾给出汇总。

## 在自动化程序中使用诊断码

自动化程序可依据完整的 `code` 选择分支，并另行读取进程退出状态。同一诊断码的 `message`
可能随版本增加上下文，因此不适合作为稳定匹配条件。若程序遇到尚未识别的诊断码，可以
保留整条记录，并依据 `severity` 决定是否继续。

诊断码前缀通常对应以下功能范围：

| 前缀 | 功能范围 |
| --- | --- |
| `config.*`、`doctor.*` | 本机配置与运行环境检查 |
| `project.*`、`case.*`、`data.*` | 项目文档、资料规划与资料锁 |
| `daemon.*`、`job_backend.*`、`scheduler.*` | 本地任务服务、任务数据库与调度准入 |
| `job.*`、`worker.*`、`run.*` | 执行轮次生命周期与数值工作进程 |
| `met.*` | 气象资料探测或查询重放 |
| `result.*`、`report.*` | 结果检查、验证、轨迹读取与报告生成 |

## 源码索引

下表从实际 Rust 实现中的字符串常量生成。需要追踪某个诊断码发出位置时，可沿源码链接
查看相应分支。若已知运行症状，也可以从[运维故障索引](../operations/troubleshooting.md)开始。

{zh_body}
"""
    return {
        DOCS / "en" / "reference" / "diagnostics.md": en,
        DOCS / "zh-CN" / "reference" / "diagnostics.md": zh,
    }


def generated_pages(help_text: str) -> dict[Path, str]:
    return cli_pages(help_text) | schema_pages() | diagnostics_pages()


def write_or_check(pages: dict[Path, str], check: bool) -> None:
    stale = []
    for path, content in pages.items():
        normalized = content.rstrip() + "\n"
        if check:
            if not path.is_file() or path.read_text(encoding="utf-8") != normalized:
                stale.append(path.relative_to(ROOT).as_posix())
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(normalized, encoding="utf-8", newline="\n")
    if stale:
        raise RuntimeError("generated reference pages are stale: " + ", ".join(stale))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--binary", type=Path, default=default_binary())
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    help_text = binary_help(args.binary.resolve())
    pages = generated_pages(help_text)
    write_or_check(pages, args.check)
    print(f"validated {len(pages)} generated reference pages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
