#!/usr/bin/env python3
"""Generate source-backed M5.1 CLI, schema, and diagnostic reference pages."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs" / "user"
CONTRACT_PATH = ROOT / "testdata" / "M5_CLI_CONTRACT.v1.json"
GENERATED_NOTICE = "<!-- Generated by tools/generate_m5_1_reference.py; do not edit. -->"

PRODUCT_SCHEMAS = (
    "M5_CONFIG.schema.json",
    "M5_PROJECT_INDEX.schema.json",
    "M5_DATA_PLAN.schema.json",
    "M5_CLI_OUTPUT.schema.json",
    "M5_CLI_STREAM_ITEM.schema.json",
    "M5_JOB_RECORD.schema.json",
    "M5_JOB_EVENT.schema.json",
    "M5_PRUNE_PLAN.schema.json",
    "M5_RESULT_INSPECTION.schema.json",
    "M5_TRAJECTORY_RECORD.schema.json",
    "M5_TRAJECTORY_STREAM.schema.json",
    "M4_RUN_MANIFEST.schema.json",
    "M4_PROVENANCE_BUNDLE.schema.json",
    "M5_BUILD_MANIFEST.schema.json",
)

EXAMPLES = {
    "M5_CONFIG.schema.json": "M5_CONFIG.example.toml",
    "M5_PROJECT_INDEX.schema.json": "M5_PROJECT_INDEX.example.yaml",
    "M5_DATA_PLAN.schema.json": "M5_DATA_PLAN.example.json",
    "M5_CLI_OUTPUT.schema.json": "M5_CLI_OUTPUT.example.json",
    "M5_CLI_STREAM_ITEM.schema.json": "M5_CLI_STREAM_ITEM.example.json",
    "M5_JOB_RECORD.schema.json": "M5_JOB_RECORD.example.json",
    "M5_JOB_EVENT.schema.json": "M5_JOB_EVENT.example.json",
    "M5_PRUNE_PLAN.schema.json": "M5_PRUNE_PLAN.example.json",
    "M5_RESULT_INSPECTION.schema.json": "M5_RESULT_INSPECTION.example.json",
    "M5_TRAJECTORY_RECORD.schema.json": "M5_TRAJECTORY_RECORD.example.json",
    "M5_TRAJECTORY_STREAM.schema.json": "M5_TRAJECTORY_STREAM.example.json",
    "M5_BUILD_MANIFEST.schema.json": "M5_BUILD_MANIFEST.example.json",
}

DIAGNOSTIC_PREFIXES = {
    "case",
    "cli",
    "command",
    "config",
    "daemon",
    "data",
    "doctor",
    "job",
    "job_backend",
    "manifest",
    "met",
    "project",
    "report",
    "result",
    "run",
    "scheduler",
    "worker",
}
CODE_PATTERN = re.compile(r'"([a-z][a-z0-9_-]*(?:\.[a-z][a-z0-9_-]*)+)"')
NON_DIAGNOSTIC_CODES = {"config.toml"}


def default_binary() -> Path:
    suffix = ".exe" if sys.platform == "win32" else ""
    return ROOT / "target" / "debug" / f"trajecta-cli{suffix}"


def binary_help(binary: Path) -> str:
    if not binary.is_file():
        raise RuntimeError(f"CLI binary does not exist: {binary}")
    completed = subprocess.run(
        [str(binary), "--help"],
        cwd=ROOT,
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if completed.returncode != 0 or completed.stderr:
        raise RuntimeError(
            f"CLI help failed with exit {completed.returncode}: "
            f"{completed.stderr.decode('utf-8', errors='replace')}"
        )
    return completed.stdout.decode("utf-8").replace("\r\n", "\n").rstrip()


def command_synopses(help_text: str) -> list[str]:
    try:
        block = help_text.split("Commands:\n", 1)[1].split("\n\nmet probe options:", 1)[0]
    except IndexError as error:
        raise RuntimeError("CLI help has no parseable Commands section") from error
    return [line.strip() for line in block.splitlines() if line.strip()]


def command_path(synopsis: str, known: set[str]) -> str:
    matches = [path for path in known if synopsis == path or synopsis.startswith(path + " ")]
    if not matches:
        raise RuntimeError(f"help synopsis has no command contract entry: {synopsis}")
    return max(matches, key=len)


def cli_pages(help_text: str) -> dict[Path, str]:
    contract = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))
    entries = {entry["path"]: entry for entry in contract["commands"]}
    entries["run report"] = {
        "path": "run report",
        "stage": "m5_a3",
        "owner": "b",
        "streaming": False,
    }
    synopses = command_synopses(help_text)
    paths = [command_path(synopsis, set(entries)) for synopsis in synopses]
    if len(paths) != len(set(paths)):
        raise RuntimeError("CLI help contains a duplicate command synopsis")
    if set(paths) != set(entries):
        missing = sorted(set(entries) - set(paths))
        extra = sorted(set(paths) - set(entries))
        raise RuntimeError(f"CLI help/contract drift: missing={missing}, extra={extra}")

    rows = []
    for synopsis, path in zip(synopses, paths, strict=True):
        entry = entries[path]
        rows.append(
            f"| `{synopsis}` | `{entry['stage']}` | "
            f"{'yes' if entry['streaming'] else 'no'} |"
        )
    en = f"""---
title: CLI command tree
description: Complete Trajecta 0.1.0-alpha.1 command synopsis generated from the real binary help and checked against the frozen CLI contract.
---

{GENERATED_NOTICE}

# CLI command tree

This page is generated from the `trajecta --help` output produced by the current
binary. Every frozen command is cross-checked against
`testdata/M5_CLI_CONTRACT.v1.json`. `run report` is an implemented M5-A3 command
that post-dates the frozen 35-command contract.

## Global rules

- Global options may appear before or after a command.
- Human output is the default. Use `--format json` for one envelope and
  `--format jsonl` for streams.
- `run` waits in the foreground unless `--detach` is supplied.
- `job prune` is dry-run only in this alpha release.

## Commands

| Synopsis | Introduced | Streaming |
| --- | --- | --- |
{chr(10).join(rows)}

## Exact binary help

```text
{help_text}
```
"""
    zh_rows = [
        row.replace("| yes |", "| 是 |").replace("| no |", "| 否 |") for row in rows
    ]
    zh = f"""---
title: CLI 命令树
description: 由真实二进制帮助生成，并与冻结 CLI 合同校验的 Trajecta 0.1.0-alpha.1 完整命令概要。
---

{GENERATED_NOTICE}

# CLI 命令树

本页由当前二进制的 `trajecta --help` 输出生成。冻结命令同时与
`testdata/M5_CLI_CONTRACT.v1.json` 交叉校验。`run report` 是 M5-A3 已实现命令，
其实现时间晚于冻结的 35 条命令合同。

## 全局规则

- 全局选项可以位于命令前后。
- 默认输出供人类阅读。单个机器结果使用 `--format json`，流式结果使用
  `--format jsonl`。
- `run` 默认在前台等待；`--detach` 用于提交后返回。
- 当前 alpha 版本的 `job prune` 只生成 dry-run 计划。

## 命令

| 概要 | 引入阶段 | 流式输出 |
| --- | --- | --- |
{chr(10).join(zh_rows)}

## 二进制原始帮助

```text
{help_text}
```
"""
    return {
        DOCS / "en" / "reference" / "cli.md": en,
        DOCS / "zh-CN" / "reference" / "cli.md": zh,
    }


def schema_rows(locale: str) -> list[str]:
    rows = []
    for name in PRODUCT_SCHEMAS:
        path = ROOT / "testdata" / name
        schema = json.loads(path.read_text(encoding="utf-8"))
        required = schema.get("required", [])
        required_text = ", ".join(f"`{item}`" for item in required) or "—"
        source = f"https://github.com/origin652/trajecta/blob/main/trajecta/testdata/{name}"
        example_name = EXAMPLES.get(name)
        if example_name:
            example_url = (
                "https://github.com/origin652/trajecta/blob/main/trajecta/testdata/"
                + example_name
            )
            example = f"[{example_name}]({example_url})"
        else:
            example = "—"
        title = schema.get("title", name)
        schema_link = f"[{name}]({source})"
        rows.append(f"| {title} | {schema_link} | {example} | {required_text} |")
    return rows


def schema_pages() -> dict[Path, str]:
    rows = "\n".join(schema_rows("en"))
    en = f"""---
title: JSON and JSONL schemas
description: Source-backed schemas for Trajecta configuration, control-plane streams, results, manifests, provenance, and package metadata.
---

{GENERATED_NOTICE}

# JSON and JSONL schemas

The schema files are the normative machine-readable definitions. Examples are
validation fixtures, not substitutes for the schemas. Case and RunProfile use
their public YAML document contracts; see [Project, Case, and Profile](documents.md).

| Product | Schema | Example | Required top-level fields |
| --- | --- | --- | --- |
{rows}

Schema versions identify disk and stream formats independently of the software
version. M5.1 does not introduce a new schema version.
"""
    zh = f"""---
title: JSON 与 JSONL schema
description: Trajecta 配置、控制面流、结果、manifest、provenance 和安装包元数据的源码驱动 schema。
---

{GENERATED_NOTICE}

# JSON 与 JSONL schema

Schema 文件是规范的机器可读定义。示例属于校验 fixture，不能代替 schema。Case 与
RunProfile 使用公开 YAML 文档合同，详见 [Project、Case 与 Profile](documents.md)。

| 产品 | Schema | 示例 | 顶层必填字段 |
| --- | --- | --- | --- |
{rows}

Schema 版本独立标识磁盘或流格式，不随软件版本自动增加。M5.1 不引入新的 schema 版本。
"""
    return {
        DOCS / "en" / "reference" / "schemas.md": en,
        DOCS / "zh-CN" / "reference" / "schemas.md": zh,
    }


def diagnostic_sources() -> dict[str, set[str]]:
    roots = (
        ROOT / "crates" / "trajecta-cli" / "src",
        ROOT / "crates" / "trajecta-job" / "src",
    )
    found: dict[str, set[str]] = {}
    for source_root in roots:
        for path in sorted(source_root.rglob("*.rs")):
            relative = path.relative_to(ROOT).as_posix()
            text = path.read_text(encoding="utf-8")
            for code in CODE_PATTERN.findall(text):
                if (
                    code not in NON_DIAGNOSTIC_CODES
                    and code.split(".", 1)[0] in DIAGNOSTIC_PREFIXES
                ):
                    found.setdefault(code, set()).add(relative)
    return found


def diagnostics_pages() -> dict[Path, str]:
    found = diagnostic_sources()
    if not found:
        raise RuntimeError("no source-backed diagnostics found")
    groups: dict[str, list[tuple[str, set[str]]]] = {}
    for code, sources in sorted(found.items()):
        groups.setdefault(code.split(".", 1)[0], []).append((code, sources))

    sections = []
    for prefix, entries in groups.items():
        rows = []
        for code, sources in entries:
            links = []
            for source in sorted(sources):
                url = f"https://github.com/origin652/trajecta/blob/main/trajecta/{source}"
                links.append(f"[`{source}`]({url})")
            rows.append(f"| `{code}` | {', '.join(links)} |")
        sections.append(f"## `{prefix}.*`\n\n| Code | Source |\n| --- | --- |\n" + "\n".join(rows))
    body = "\n\n".join(sections)
    en = f"""---
title: Diagnostic codes
description: Source-backed index of stable Trajecta CLI, daemon, worker, job, project, data, and result diagnostic codes.
---

{GENERATED_NOTICE}

# Diagnostic codes

Machine output identifies a condition by `diagnostics[].code`; messages provide
context and may become more precise. Automation should branch on the code. The
index below is rebuilt from production Rust sources, so a documented code cannot
exist without a corresponding implementation site.

Start troubleshooting by symptom in the [operations index](../operations/troubleshooting.md).

{body}
"""
    zh = f"""---
title: Diagnostic code
description: 由源码生成的 Trajecta CLI、daemon、worker、任务、项目、资料和结果稳定诊断码索引。
---

{GENERATED_NOTICE}

# Diagnostic code

机器输出通过 `diagnostics[].code` 标识条件；message 提供上下文，措辞可能进一步细化。
自动化程序应按 code 分支。下列索引从生产 Rust 源码重建，因此每个已记录 code 都有对应
实现位置。

按症状排查时，请先查阅[运维故障索引](../operations/troubleshooting.md)。

{body}
"""
    return {
        DOCS / "en" / "reference" / "diagnostics.md": en,
        DOCS / "zh-CN" / "reference" / "diagnostics.md": zh,
    }


def generated_pages(help_text: str) -> dict[Path, str]:
    return cli_pages(help_text) | schema_pages() | diagnostics_pages()


def write_or_check(pages: dict[Path, str], check: bool) -> None:
    stale = []
    for path, content in pages.items():
        normalized = content.rstrip() + "\n"
        if check:
            if not path.is_file() or path.read_text(encoding="utf-8") != normalized:
                stale.append(path.relative_to(ROOT).as_posix())
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(normalized, encoding="utf-8", newline="\n")
    if stale:
        raise RuntimeError("generated reference pages are stale: " + ", ".join(stale))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--binary", type=Path, default=default_binary())
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    help_text = binary_help(args.binary.resolve())
    pages = generated_pages(help_text)
    write_or_check(pages, args.check)
    print(f"validated {len(pages)} generated reference pages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
