#!/usr/bin/env python3
"""Generate source-backed M5.1 CLI, schema, and diagnostic reference pages."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs" / "user"
CONTRACT_PATH = ROOT / "testdata" / "M5_CLI_CONTRACT.v1.json"
GENERATED_NOTICE = "<!-- Generated by tools/generate_m5_1_reference.py; do not edit. -->"

PRODUCT_SCHEMAS = (
    "M5_CONFIG.schema.json",
    "M5_PROJECT_INDEX.schema.json",
    "M5_DATA_PLAN.schema.json",
    "M5_CLI_OUTPUT.schema.json",
    "M5_CLI_STREAM_ITEM.schema.json",
    "M5_JOB_RECORD.schema.json",
    "M5_JOB_EVENT.schema.json",
    "M5_PRUNE_PLAN.schema.json",
    "M5_RESULT_INSPECTION.schema.json",
    "M5_TRAJECTORY_RECORD.schema.json",
    "M5_TRAJECTORY_STREAM.schema.json",
    "M4_RUN_MANIFEST.schema.json",
    "M4_PROVENANCE_BUNDLE.schema.json",
    "M5_BUILD_MANIFEST.schema.json",
)

EXAMPLES = {
    "M5_CONFIG.schema.json": "M5_CONFIG.example.toml",
    "M5_PROJECT_INDEX.schema.json": "M5_PROJECT_INDEX.example.yaml",
    "M5_DATA_PLAN.schema.json": "M5_DATA_PLAN.example.json",
    "M5_CLI_OUTPUT.schema.json": "M5_CLI_OUTPUT.example.json",
    "M5_CLI_STREAM_ITEM.schema.json": "M5_CLI_STREAM_ITEM.example.json",
    "M5_JOB_RECORD.schema.json": "M5_JOB_RECORD.example.json",
    "M5_JOB_EVENT.schema.json": "M5_JOB_EVENT.example.json",
    "M5_PRUNE_PLAN.schema.json": "M5_PRUNE_PLAN.example.json",
    "M5_RESULT_INSPECTION.schema.json": "M5_RESULT_INSPECTION.example.json",
    "M5_TRAJECTORY_RECORD.schema.json": "M5_TRAJECTORY_RECORD.example.json",
    "M5_TRAJECTORY_STREAM.schema.json": "M5_TRAJECTORY_STREAM.example.json",
    "M5_BUILD_MANIFEST.schema.json": "M5_BUILD_MANIFEST.example.json",
}

DIAGNOSTIC_PREFIXES = {
    "case",
    "cli",
    "command",
    "config",
    "daemon",
    "data",
    "doctor",
    "job",
    "job_backend",
    "manifest",
    "met",
    "project",
    "report",
    "result",
    "run",
    "scheduler",
    "worker",
}
CODE_PATTERN = re.compile(r'"([a-z][a-z0-9_-]*(?:\.[a-z][a-z0-9_-]*)+)"')
NON_DIAGNOSTIC_CODES = {"config.toml"}

COMMAND_PURPOSES = {
    "config init": ("Create a machine configuration at the selected path", "在所选路径创建机器配置"),
    "config path": ("Print the selected machine-configuration path", "显示当前选择的机器配置路径"),
    "config list": ("List every configuration leaf and its value", "列出全部配置 leaf 及其值"),
    "config get": ("Read one configuration selector", "读取一个配置 selector"),
    "config set": ("Validate and atomically update one selector", "校验并原子更新一个 selector"),
    "config unset": ("Remove an optional selector", "移除一个 optional selector"),
    "config validate": ("Validate the complete selected configuration", "校验完整的所选配置"),
    "project init": ("Create a project index and initial directory layout", "创建 project index 与初始目录结构"),
    "project status": ("Report draft, configured, or finalized project state", "报告 draft、configured 或 finalized 项目状态"),
    "project show": ("Show the resolved project index and document summary", "显示 resolved project index 与文档摘要"),
    "project get": ("Read one project selector", "读取一个 project selector"),
    "project set": ("Validate and update one project selector", "校验并更新一个 project selector"),
    "project unset": ("Remove an optional project selector", "移除一个 optional project selector"),
    "project validate": ("Validate the index and referenced Case and Profile documents", "校验 index 及其引用的 Case 与 Profile 文档"),
    "project data-plan": ("Calculate deterministic dataset requirements and local status", "计算确定性资料需求及其本地状态"),
    "project finalize": ("Inspect prepared data and atomically bind DatasetLocks", "检查已准备资料并原子绑定 DatasetLock"),
    "case validate": ("Validate a Case for a selected intent", "按指定 intent 校验 Case"),
    "case resolve": ("Expand a Case into its resolved public document", "将 Case 展开为 resolved public document"),
    "data inspect": ("Inspect one supported meteorological file", "检查一个受支持的气象资料文件"),
    "data lock": ("Build a DatasetLock from a Case, profile, and data root", "根据 Case、profile 与 data root 构建 DatasetLock"),
    "met probe": ("Query selected meteorological points", "查询指定气象点"),
    "met replay": ("Replay a JSONL meteorological query stream", "重放 JSONL 气象查询流"),
    "doctor": ("Check configuration, project, data, filesystem, and optional deep probes", "检查配置、项目、资料、文件系统及可选 deep probe"),
    "run": ("Submit a project Profile or direct Case/Profile pair", "提交 project Profile 或直接 Case/Profile pair"),
    "job list": ("List the latest visible attempt for each job series", "列出各 job series 的最新可见 attempt"),
    "job status": ("Read the current snapshot for one job series", "读取一个 job series 的当前快照"),
    "job wait": ("Wait for the current attempt to become terminal", "等待 current attempt 进入终态"),
    "job events": ("Read or follow durable queue events", "读取或跟随持久化队列事件"),
    "job cancel": ("Request safe cancellation or force-stop the current attempt", "请求安全取消或强制停止 current attempt"),
    "job rerun": ("Create the next attempt in an existing series", "在现有 series 中创建下一个 attempt"),
    "job forget": ("Hide a terminal series from routine list output", "从日常列表隐藏 terminal series"),
    "job prune": ("Return the dry-run storage-prune plan", "返回 dry-run 存储清理计划"),
    "result inspect": ("Summarize a run manifest, artifacts, and available SQLite counts", "汇总 run manifest、artifact 与可用 SQLite count"),
    "result verify": ("Run quick or full product verification", "执行 quick 或 full product verification"),
    "result trajectory": ("Stream trajectory rows for selected or all particles", "流式读取指定粒子或全部粒子的 trajectory row"),
    "run report": ("Create or refresh RESULT/run-report.md", "创建或刷新 RESULT/run-report.md"),
}


def default_binary() -> Path:
    suffix = ".exe" if sys.platform == "win32" else ""
    return ROOT / "target" / "debug" / f"trajecta-cli{suffix}"


def binary_help(binary: Path) -> str:
    if not binary.is_file():
        raise RuntimeError(f"CLI binary does not exist: {binary}")
    completed = subprocess.run(
        [str(binary), "--help"],
        cwd=ROOT,
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if completed.returncode != 0 or completed.stderr:
        raise RuntimeError(
            f"CLI help failed with exit {completed.returncode}: "
            f"{completed.stderr.decode('utf-8', errors='replace')}"
        )
    return completed.stdout.decode("utf-8").replace("\r\n", "\n").rstrip()


def command_synopses(help_text: str) -> list[str]:
    try:
        block = help_text.split("Commands:\n", 1)[1].split("\n\nmet probe options:", 1)[0]
    except IndexError as error:
        raise RuntimeError("CLI help has no parseable Commands section") from error
    return [line.strip() for line in block.splitlines() if line.strip()]


def command_path(synopsis: str, known: set[str]) -> str:
    matches = [path for path in known if synopsis == path or synopsis.startswith(path + " ")]
    if not matches:
        raise RuntimeError(f"help synopsis has no command contract entry: {synopsis}")
    return max(matches, key=len)


def cli_pages(help_text: str) -> dict[Path, str]:
    contract = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))
    entries = {entry["path"]: entry for entry in contract["commands"]}
    entries["run report"] = {
        "path": "run report",
        "stage": "m5_a3",
        "owner": "b",
        "streaming": False,
    }
    synopses = command_synopses(help_text)
    paths = [command_path(synopsis, set(entries)) for synopsis in synopses]
    if len(paths) != len(set(paths)):
        raise RuntimeError("CLI help contains a duplicate command synopsis")
    if set(paths) != set(entries):
        missing = sorted(set(entries) - set(paths))
        extra = sorted(set(paths) - set(entries))
        raise RuntimeError(f"CLI help/contract drift: missing={missing}, extra={extra}")

    if set(COMMAND_PURPOSES) != set(entries):
        missing = sorted(set(entries) - set(COMMAND_PURPOSES))
        extra = sorted(set(COMMAND_PURPOSES) - set(entries))
        raise RuntimeError(f"CLI purpose drift: missing={missing}, extra={extra}")

    rows = []
    zh_rows = []
    for synopsis, path in zip(synopses, paths, strict=True):
        entry = entries[path]
        output = "JSONL capable" if entry["streaming"] else "single response"
        zh_output = "可使用 JSONL" if entry["streaming"] else "单次响应"
        rows.append(f"| `{synopsis}` | {COMMAND_PURPOSES[path][0]} | {output} |")
        zh_rows.append(f"| `{synopsis}` | {COMMAND_PURPOSES[path][1]} | {zh_output} |")
    en = f"""---
title: CLI command tree
description: Complete Trajecta 0.1.0-alpha.1 command synopsis generated from the real binary help and checked against the frozen CLI contract.
---

{GENERATED_NOTICE}

# CLI command tree

This page is generated from the `trajecta --help` output produced by the current
binary. Every command is cross-checked against
`testdata/M5_CLI_CONTRACT.v1.json`; the implemented `run report` command is
checked alongside that frozen contract.

## Command form

```text
trajecta [GLOBAL OPTIONS] COMMAND [ARGUMENTS]
```

Global options may appear before or after a command. `--config PATH` selects
the machine configuration and therefore the local daemon endpoint and job
catalog. `--project PATH` selects a project root or its index for project-aware
commands.

| Option | Meaning |
| --- | --- |
| `--format human` | Human-readable output; this is the default |
| `--format json` | One `trajecta.cli-output/v1` envelope |
| `--format jsonl` | One `trajecta.cli-stream-item/v1` object per line for a stream-capable command |
| `--json` | Alias for `--format json` |
| `--config PATH` | Explicit machine configuration, ahead of environment and platform defaults |
| `--project PATH` | Explicit project root or `trajecta-project.yaml` path |
| `-h`, `--help` | Display command help |

## Argument conventions

| Placeholder | Accepted value |
| --- | --- |
| `PATH`, `FILE`, `DIR` | Filesystem path; project document paths remain inside the project jail |
| `KEY`, `SELECTOR` | Dotted configuration or project selector |
| `JOB_ID` | Job-series identifier returned by run admission |
| `RESULT` | Job-series ID, run ID, or result-directory path accepted by result commands |
| `UNIX` | Integer UTC Unix timestamp in seconds |
| `JSONL` | Newline-delimited JSON file path; selected meteorology commands also accept `-` for standard input or output |

## Runtime behavior

- `run` waits in the foreground unless `--detach` is supplied. Detached mode
  returns after durable queue admission.
- A foreground run exits after the attempt becomes terminal. Use `job status`,
  `job wait`, or `job events` to reconnect from another terminal.
- `job events`, meteorological streams, and trajectory output can use JSONL.
  Their final stream item is a summary.
- `job prune` returns a dry-run plan in this alpha release. It has no delete or
  apply option.
- Application errors in machine mode use the same envelope shape as successful
  commands. Process exit codes remain available to shell scripts.

## Commands

| Synopsis | Purpose | Machine output |
| --- | --- | --- |
{chr(10).join(rows)}

The procedural guides provide complete sequences for
[project preparation](../how-to/progressive-configuration.md),
[queue operation](../how-to/run-queue.md), and
[result reading](../how-to/results.md).

## Exact binary help

```text
{help_text}
```
"""
    zh = f"""---
title: CLI 命令树
description: 由真实二进制帮助生成，并与冻结 CLI 合同校验的 Trajecta 0.1.0-alpha.1 完整命令概要。
---

{GENERATED_NOTICE}

# CLI 命令树

本页由当前二进制的 `trajecta --help` 输出生成。全部命令与
`testdata/M5_CLI_CONTRACT.v1.json` 交叉校验；已经实现的 `run report` 会与该冻结合同一同
检查。

## 命令形式

```text
trajecta [GLOBAL OPTIONS] COMMAND [ARGUMENTS]
```

Global option 可以位于命令前后。`--config PATH` 选择机器配置，进而确定本地 daemon
endpoint 与 job catalog。`--project PATH` 为 project-aware command 选择项目根或 index。

| Option | 含义 |
| --- | --- |
| `--format human` | Human-readable output，也是默认格式 |
| `--format json` | 一个 `trajecta.cli-output/v1` envelope |
| `--format jsonl` | Stream-capable command 每行一个 `trajecta.cli-stream-item/v1` object |
| `--json` | `--format json` 的 alias |
| `--config PATH` | 显式机器配置，优先于环境变量和平台默认路径 |
| `--project PATH` | 显式 project root 或 `trajecta-project.yaml` 路径 |
| `-h`、`--help` | 显示 command help |

## 参数名称

| Placeholder | 接受的值 |
| --- | --- |
| `PATH`、`FILE`、`DIR` | 文件系统路径；项目文档路径保持在 project jail 内 |
| `KEY`、`SELECTOR` | Dotted configuration 或 project selector |
| `JOB_ID` | Run admission 返回的 job-series identifier |
| `RESULT` | Result command 接受的 job-series ID、run ID 或结果目录路径 |
| `UNIX` | 以秒表示的 UTC Unix timestamp integer |
| `JSONL` | Newline-delimited JSON file path；指定 meteorological command 还可使用 `-` 表示 standard input 或 output |

## Runtime 行为

- `run` 默认在前台等待；`--detach` 在任务持久化接收后返回。
- Foreground run 会等待 attempt 进入终态。另一个终端可通过 `job status`、`job wait` 或
  `job events` 重新连接。
- `job events`、meteorological stream 与 trajectory output 可以使用 JSONL，最后一个 stream
  item 为 summary。
- 当前 alpha 版本的 `job prune` 返回 dry-run plan，没有 delete 或 apply option。
- Machine mode 中的 application error 与成功命令使用相同 envelope shape。Shell script
  仍可读取 process exit code。

## 命令

| 概要 | 用途 | Machine output |
| --- | --- | --- |
{chr(10).join(zh_rows)}

完整操作顺序见[项目准备](../how-to/progressive-configuration.md)、
[队列运行](../how-to/run-queue.md)与[结果读取](../how-to/results.md)。

## 二进制原始帮助

```text
{help_text}
```
"""
    return {
        DOCS / "en" / "reference" / "cli.md": en,
        DOCS / "zh-CN" / "reference" / "cli.md": zh,
    }


def schema_rows(locale: str) -> list[str]:
    rows = []
    for name in PRODUCT_SCHEMAS:
        path = ROOT / "testdata" / name
        schema = json.loads(path.read_text(encoding="utf-8"))
        required = schema.get("required", [])
        required_text = ", ".join(f"`{item}`" for item in required) or "—"
        source = f"https://github.com/origin652/trajecta/blob/main/trajecta/testdata/{name}"
        example_name = EXAMPLES.get(name)
        if example_name:
            example_url = (
                "https://github.com/origin652/trajecta/blob/main/trajecta/testdata/"
                + example_name
            )
            example = f"[{example_name}]({example_url})"
        else:
            example = "—"
        title = schema.get("title", name)
        schema_link = f"[{name}]({source})"
        rows.append(f"| {title} | {schema_link} | {example} | {required_text} |")
    return rows


def schema_pages() -> dict[Path, str]:
    rows = "\n".join(schema_rows("en"))
    en = f"""---
title: JSON and JSONL schemas
description: Source-backed schemas for Trajecta configuration, control-plane streams, results, manifests, provenance, and package metadata.
---

{GENERATED_NOTICE}

# JSON and JSONL schemas

Trajecta versions each machine-readable disk or stream format independently.
The `schema_version` inside a document selects that format contract; the
software version identifies the executable that reads or writes it. M5.1 keeps
the existing schema identifiers.

The linked schema files define required fields, value types, enumerations,
additional-property rules, and nested records. Examples show one valid instance
and are also used as validation fixtures. Case and RunProfile follow their
public YAML document contracts; see
[Project, Case, and Profile](documents.md).

## Schema families

| Family | Formats | Where they appear |
| --- | --- | --- |
| Configuration and project | Machine configuration, project index, data plan | Files edited during local and project setup |
| CLI response | Single JSON envelope and JSONL stream item | Standard output in machine mode |
| Job control | Job record, job event, prune plan | Local daemon queries and queue history |
| Result reading | Result inspection, trajectory record, trajectory stream | `result inspect` and `result trajectory` output |
| Scientific product | Run manifest and provenance bundle | Every completed result directory |
| Distribution | Build manifest | Release package root |

## Machine-output envelopes

`trajecta.cli-output/v1` represents one command response. It contains the full
command path, an `ok` flag, a command-specific `data` value, and structured
diagnostics. A usage error in JSON mode uses the same outer format while
retaining process exit code `2`.

`trajecta.cli-stream-item/v1` represents one JSONL line. Its `kind` selects a
data item, diagnostic, or final summary. The outer `sequence` orders lines in
that invocation. A job event inside `data` has its own durable global sequence
for reconnection.

## Documents on disk

The configuration and project-index schemas reject unknown properties and
invalid value types. Product commands validate them before an atomic update.
The data plan is generated from resolved project requirements and local status;
it can be written to a file and reviewed before data preparation.

The run manifest and provenance bundle are immutable result identities after a
successful closeout. Open them through `result inspect` and `result verify`
when possible, since those commands also check their relationship with SQLite
and the selected attempt.

## Schema index

| Product | Schema | Example | Required top-level fields |
| --- | --- | --- | --- |
{rows}

Schema versions identify disk and stream formats independently of the software
version. Automation can select a parser from `schema_version` before reading
command-specific fields. The [exit-code reference](exit-codes.md) explains how
schema-valid machine output relates to process status.
"""
    zh = f"""---
title: JSON 与 JSONL schema
description: Trajecta 配置、控制面流、结果、manifest、provenance 和安装包元数据的源码驱动 schema。
---

{GENERATED_NOTICE}

# JSON 与 JSONL schema

Trajecta 为每种 machine-readable disk 或 stream format 单独设置版本。文档中的
`schema_version` 选择 format contract，software version 则标识读写它的 executable。M5.1
保持已有 schema identifier。

链接中的 schema file 定义 required field、value type、enumeration、additional-property rule
与 nested record。Example 展示一份 valid instance，同时用于 validation fixture。Case 与
RunProfile 使用公开 YAML document contract，详见
[Project、Case 与 Profile](documents.md)。

## Schema family

| Family | Format | 出现位置 |
| --- | --- | --- |
| 配置与项目 | Machine configuration、project index、data plan | 本机与项目设置期间编辑或生成的文件 |
| CLI response | Single JSON envelope 与 JSONL stream item | Machine mode standard output |
| Job control | Job record、job event、prune plan | Local daemon query 与 queue history |
| 结果读取 | Result inspection、trajectory record、trajectory stream | `result inspect` 与 `result trajectory` 输出 |
| 科学产品 | Run manifest 与 provenance bundle | 每个完成结果目录 |
| 分发 | Build manifest | Release package root |

## Machine-output envelope

`trajecta.cli-output/v1` 表示一次 command response，其中包含完整 command path、`ok` flag、
command-specific `data` value 与 structured diagnostic。JSON mode 中的 usage error 使用相同
outer format，同时保留 process exit code `2`。

`trajecta.cli-stream-item/v1` 表示一行 JSONL。`kind` 用于选择 data item、diagnostic 或最终
summary。外层 `sequence` 对本次 invocation 中的行排序。`data` 内的 job event 还有自己的
durable global sequence，用于重新连接。

## 磁盘文档

Configuration 与 project-index schema 会拒绝 unknown property 和 invalid value type。Product
command 在 atomic update 前校验完整文档。Data plan 根据 resolved project requirement 与
local status 生成，可以写入文件，并在准备资料前审阅。

Run manifest 与 provenance bundle 在成功收尾后成为 immutable result identity。通常可通过
`result inspect` 与 `result verify` 打开，因为这两条命令还会检查它们与 SQLite、selected
attempt 的关系。

## Schema 索引

| 产品 | Schema | 示例 | 顶层必填字段 |
| --- | --- | --- | --- |
{rows}

Schema version 独立标识磁盘或流格式，不随 software version 自动增加。Automation 可以先
根据 `schema_version` 选择 parser，再读取 command-specific field。[Exit code 参考](exit-codes.md)
说明 schema-valid machine output 与 process status 的关系。
"""
    return {
        DOCS / "en" / "reference" / "schemas.md": en,
        DOCS / "zh-CN" / "reference" / "schemas.md": zh,
    }


def diagnostic_sources() -> dict[str, set[str]]:
    roots = (
        ROOT / "crates" / "trajecta-cli" / "src",
        ROOT / "crates" / "trajecta-job" / "src",
    )
    found: dict[str, set[str]] = {}
    for source_root in roots:
        for path in sorted(source_root.rglob("*.rs")):
            relative = path.relative_to(ROOT).as_posix()
            text = path.read_text(encoding="utf-8")
            for code in CODE_PATTERN.findall(text):
                if (
                    code not in NON_DIAGNOSTIC_CODES
                    and code.split(".", 1)[0] in DIAGNOSTIC_PREFIXES
                ):
                    found.setdefault(code, set()).add(relative)
    return found


def diagnostics_pages() -> dict[Path, str]:
    found = diagnostic_sources()
    if not found:
        raise RuntimeError("no source-backed diagnostics found")
    groups: dict[str, list[tuple[str, set[str]]]] = {}
    for code, sources in sorted(found.items()):
        groups.setdefault(code.split(".", 1)[0], []).append((code, sources))

    sections = []
    for prefix, entries in groups.items():
        rows = []
        for code, sources in entries:
            links = []
            for source in sorted(sources):
                url = f"https://github.com/origin652/trajecta/blob/main/trajecta/{source}"
                links.append(f"[`{source}`]({url})")
            rows.append(f"| `{code}` | {', '.join(links)} |")
        sections.append(f"## `{prefix}.*`\n\n| Code | Source |\n| --- | --- |\n" + "\n".join(rows))
    body = "\n\n".join(sections)
    en = f"""---
title: Diagnostic codes
description: Source-backed index of stable Trajecta CLI, daemon, worker, job, project, data, and result diagnostic codes.
---

{GENERATED_NOTICE}

# Diagnostic codes

Machine output identifies a condition through `diagnostics[].code`. Codes are
short, stable selectors for scripts and troubleshooting; messages add the path,
value, operating-system error, or run identity relevant to one invocation.

## Diagnostic record

| Field | Content |
| --- | --- |
| `severity` | `error`, `warning`, or `info` |
| `code` | Namespaced condition such as `project.lock_missing` |
| `message` | Human-readable detail for this occurrence |
| `path` | Ordered field or array-index components locating a document value |
| `hint` | Optional next command or correction |

An envelope can contain several diagnostics. `project finalize`, for example,
can return one preflight failure with nested project or data conditions. Read
all entries before changing a document. In JSONL, a diagnostic is a stream item
with `kind: "diagnostic"`; a later summary closes the stream.

## Using codes in automation

Branch on the complete code and inspect the process exit status separately.
The message can gain more context between releases without changing the
condition selected by the code. Unknown codes are best retained in logs and
handled as the severity indicates, allowing a newer producer to communicate
with an older monitoring script.

The namespace usually identifies the component:

| Prefix | Area |
| --- | --- |
| `config.*`, `doctor.*` | Machine configuration and environment checks |
| `project.*`, `case.*`, `data.*` | Project documents, dataset planning, and locks |
| `daemon.*`, `job_backend.*`, `scheduler.*` | Local control plane, catalog, and admission |
| `job.*`, `worker.*`, `run.*` | Attempt lifecycle and numerical worker |
| `met.*` | Meteorological probe or replay command |
| `result.*`, `report.*` | Result inspection, verification, trajectory output, and report creation |

## Source index

The list below is rebuilt from production Rust string literals. Source links
are included for contributors who are tracing the branch that emitted a code.

Start troubleshooting by symptom in the [operations index](../operations/troubleshooting.md).

{body}
"""
    zh = f"""---
title: Diagnostic code
description: 由源码生成的 Trajecta CLI、daemon、worker、任务、项目、资料和结果稳定诊断码索引。
---

{GENERATED_NOTICE}

# Diagnostic code

Machine output 通过 `diagnostics[].code` 标识条件。Code 是 script 和故障排查使用的稳定
selector；message 会加入本次 invocation 对应的 path、value、operating-system error 或
run identity。

## Diagnostic record

| Field | 内容 |
| --- | --- |
| `severity` | `error`、`warning` 或 `info` |
| `code` | 带 namespace 的 condition，例如 `project.lock_missing` |
| `message` | 本次 occurrence 的 human-readable detail |
| `path` | 定位 document value 的有序 field 或 array-index component |
| `hint` | Optional next command 或 correction |

一个 envelope 可以包含多个 diagnostic。例如，`project finalize` 可以返回一个 preflight
failure，并带有嵌套 project 或 data condition。修改文档前可以先读取全部 entry。JSONL
中的 diagnostic 是 `kind: "diagnostic"` 的 stream item，后续 summary 负责关闭 stream。

## 在 automation 中使用 code

Automation 可以按完整 code 分支，并单独读取 process exit status。Message 可以在后续版本
中增加上下文，而 condition code 保持原值。遇到未知 code 时，可将完整 entry 保留到 log，
再按 severity 处理，使较新的 producer 仍能向已有 monitoring script 提供信息。

Namespace 通常对应以下 component：

| Prefix | 区域 |
| --- | --- |
| `config.*`、`doctor.*` | Machine configuration 与 environment check |
| `project.*`、`case.*`、`data.*` | Project document、dataset plan 与 lock |
| `daemon.*`、`job_backend.*`、`scheduler.*` | Local control plane、catalog 与 admission |
| `job.*`、`worker.*`、`run.*` | Attempt lifecycle 与 numerical worker |
| `met.*` | Meteorological probe 或 replay command |
| `result.*`、`report.*` | Result inspection、verification、trajectory output 与 report creation |

## Source 索引

下表从 production Rust string literal 重建。Contributor 调查 code 的发出分支时，可以使用
其中的 source link。

按症状排查时，请先查阅[运维故障索引](../operations/troubleshooting.md)。

{body}
"""
    return {
        DOCS / "en" / "reference" / "diagnostics.md": en,
        DOCS / "zh-CN" / "reference" / "diagnostics.md": zh,
    }


def generated_pages(help_text: str) -> dict[Path, str]:
    return cli_pages(help_text) | schema_pages() | diagnostics_pages()


def write_or_check(pages: dict[Path, str], check: bool) -> None:
    stale = []
    for path, content in pages.items():
        normalized = content.rstrip() + "\n"
        if check:
            if not path.is_file() or path.read_text(encoding="utf-8") != normalized:
                stale.append(path.relative_to(ROOT).as_posix())
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(normalized, encoding="utf-8", newline="\n")
    if stale:
        raise RuntimeError("generated reference pages are stale: " + ", ".join(stale))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--binary", type=Path, default=default_binary())
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    help_text = binary_help(args.binary.resolve())
    pages = generated_pages(help_text)
    write_or_check(pages, args.check)
    print(f"validated {len(pages)} generated reference pages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
