#!/usr/bin/env python3
"""Prepare and audit the frozen M5-A5 FLEXPART comparison case.

The staging command converts the official ERA5 hybrid-137 anchors to the GRIB
layout required by FLEXPART.  It never edits the FLEXPART source tree or the
immutable source anchors, and every generated byte is covered by a manifest.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import shutil
import sqlite3
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import run_m5_a4_product_matrix as product


SCHEMA_VERSION = "trajecta.m5-a5-flexpart-case/v1"
METEOROLOGY_SCHEMA_VERSION = "trajecta.m5-a5-meteorology/v1"
TRAJECTA_CASE_SCHEMA_VERSION = "trajecta.m5-a5-trajecta-case/v1"
START_DATE = "20181201"
START_TIME = "030000"
END_DATE = "20181201"
END_TIME = "040000"
START_UNIX = 1_543_633_200
END_UNIX = 1_543_636_800

METEOROLOGY_NAMES = ("EA18120100", "EA18120103", "EA18120106", "EA18120109")
MESSAGES_PER_FRAME = 5 * 137 + 1 + 2 + 5
SOURCE_IDENTITIES = {
    "raw/era5_hybrid137_20181201.nc":
        "788e4695029c6b11bc6304b855c04d3744933dc24f9c69d8ef9f796a9170f78d",
    "raw/era5_lnsp_20181201.nc":
        "0a68ff7bb74962b357c3e0f4ca0852c754c3917e6cb2bdaca7cf39c579fd2e4a",
    "raw/era5_hybrid_surface_base_20181201.nc":
        "133b3a55408aa251f45491e44ee5ebf541dd52cc0bd807de427ac4f3f36be1a2",
    "raw/era5_hybrid_pv_probe.grib":
        "ea6e73eb680c31f358259e3dff7175f95cde26631ecb67ae438da9603da5669c",
}
TRAJECTA_ONLY_SOURCE_IDENTITIES = {
    "raw/era5_hybrid_surface_flux_20181201.nc":
        "92ab45b3fd70f65a10ba0e14f484f4a67b0d6f72f369b3387235280631ed69d6",
}
TRAJECTA_DATA_IDENTITIES = {
    "era5_hybrid137_prepared_20181201.nc":
        "eb8f8554c2ed87e0a49d8a7e5ddf52b7337c96461db7c650a8d890e3f400e0e6",
    "era5_surface_20181201.nc":
        "3c21ad12b54e559331710ada547d4fed6cdf8ece1450d7c92ec364691b51a730",
}

STATIC_OPTION_FILES = (
    "AGECLASSES",
    "IGBP_int1.dat",
    "OUTGRID",
    "OUTGRID_NEST",
    "sfcdata.t",
    "sfcdepo.t",
)


class ComparisonError(RuntimeError):
    """Stable M5-A5 preparation failure."""


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_text(path: Path, text: str) -> None:
    path.write_text(text.rstrip("\n") + "\n", encoding="utf-8", newline="\n")


def require_sha256(path: Path, expected: str) -> dict[str, object]:
    if not path.is_file():
        raise ComparisonError(f"required source missing: {path}")
    actual = sha256(path)
    if actual != expected:
        raise ComparisonError(f"source identity mismatch for {path}: {actual}")
    return {"path": path.as_posix(), "size_bytes": path.stat().st_size, "sha256": actual}


def meteorology_name(timestamp: int) -> str:
    instant = datetime.fromtimestamp(timestamp, tz=timezone.utc)
    if instant.strftime("%Y%m%d") != START_DATE or instant.minute or instant.second:
        raise ComparisonError(f"unsupported meteorology time: {instant.isoformat()}")
    return f"EA{instant:%y%m%d%H}"


def _stage_modules():
    try:
        import eccodes  # type: ignore
        import netCDF4  # type: ignore
        import numpy  # type: ignore
    except ImportError as error:
        raise ComparisonError(
            "stage-meteorology requires Python eccodes, netCDF4, and numpy"
        ) from error
    return eccodes, netCDF4, numpy


def _plain_array(numpy, variable, index: int, shape: tuple[int, ...], label: str):
    values = variable[index]
    if numpy.ma.isMaskedArray(values) and numpy.ma.getmaskarray(values).any():
        raise ComparisonError(f"masked values in {label}")
    array = numpy.asarray(values, dtype=numpy.float64)
    while array.ndim > len(shape) and array.shape[0] == 1:
        array = array[0]
    if array.shape != shape:
        raise ComparisonError(f"{label} shape {array.shape} != {shape}")
    if not numpy.isfinite(array).all():
        raise ComparisonError(f"nonfinite values in {label}")
    return array


def _write_grib_message(
    eccodes,
    template,
    stream,
    values,
    instant: datetime,
    *,
    param_id: int | None = None,
    category_number: tuple[int, int] | None = None,
    level_type: str,
    level: int | None = None,
) -> dict[str, object]:
    message = eccodes.codes_clone(template)
    try:
        eccodes.codes_set(message, "dataDate", int(instant.strftime("%Y%m%d")))
        eccodes.codes_set(message, "dataTime", int(instant.strftime("%H%M")))
        eccodes.codes_set(message, "forecastTime", 0)
        eccodes.codes_set(message, "stepRange", 0)
        if level_type != "hybrid":
            eccodes.codes_set(message, "typeOfLevel", level_type)
            if level is None:
                eccodes.codes_set(message, "scaleFactorOfFirstFixedSurface", 0)
                eccodes.codes_set(message, "scaledValueOfFirstFixedSurface", 0)
        if param_id is not None:
            eccodes.codes_set(message, "paramId", param_id)
        elif category_number is not None:
            category, number = category_number
            eccodes.codes_set(message, "discipline", 0)
            eccodes.codes_set(message, "parameterCategory", category)
            eccodes.codes_set(message, "parameterNumber", number)
        else:
            raise ComparisonError("GRIB message is missing a parameter identity")
        if level is not None:
            eccodes.codes_set(message, "level", level)
        eccodes.codes_set_values(message, values.reshape(-1))
        if eccodes.codes_get(message, "NV") != 276:
            raise ComparisonError("generated GRIB message lost the 137-level PV vector")
        eccodes.codes_write(message, stream)
        return {
            "param_id": int(eccodes.codes_get(message, "paramId")),
            "parameter_category": int(eccodes.codes_get(message, "parameterCategory")),
            "parameter_number": int(eccodes.codes_get(message, "parameterNumber")),
            "type_of_level": str(eccodes.codes_get(message, "typeOfLevel")),
            "level": int(eccodes.codes_get(message, "level")),
        }
    finally:
        eccodes.codes_release(message)


def stage_meteorology(arguments: argparse.Namespace) -> int:
    source_root = arguments.source.resolve()
    output = arguments.output.resolve()
    if output.exists():
        raise ComparisonError(f"refusing to overwrite meteorology staging: {output}")

    sources = {
        relative: require_sha256(source_root / relative, expected)
        for relative, expected in SOURCE_IDENTITIES.items()
    }
    eccodes, netcdf4, numpy = _stage_modules()
    hybrid_path = source_root / "raw/era5_hybrid137_20181201.nc"
    lnsp_path = source_root / "raw/era5_lnsp_20181201.nc"
    surface_path = source_root / "raw/era5_hybrid_surface_base_20181201.nc"
    template_path = source_root / "raw/era5_hybrid_pv_probe.grib"

    output.mkdir(parents=True)
    with (
        netcdf4.Dataset(hybrid_path.as_posix()) as hybrid,
        netcdf4.Dataset(lnsp_path.as_posix()) as lnsp,
        netcdf4.Dataset(surface_path.as_posix()) as surface,
        template_path.open("rb") as template_stream,
    ):
        template = eccodes.codes_grib_new_from_file(template_stream)
        if template is None:
            raise ComparisonError("official PV probe contains no GRIB message")
        try:
            times = numpy.asarray(hybrid.variables["valid_time"][:], dtype=numpy.int64)
            if tuple(meteorology_name(int(value)) for value in times) != METEOROLOGY_NAMES:
                raise ComparisonError(f"unexpected hybrid times: {times.tolist()}")
            for companion, label in ((lnsp, "lnsp"), (surface, "surface")):
                companion_times = numpy.asarray(
                    companion.variables["valid_time"][:], dtype=numpy.int64
                )
                if not numpy.array_equal(times, companion_times):
                    raise ComparisonError(f"{label} valid_time differs from hybrid")
                for coordinate in ("latitude", "longitude"):
                    if not numpy.array_equal(
                        hybrid.variables[coordinate][:], companion.variables[coordinate][:]
                    ):
                        raise ComparisonError(f"{label} {coordinate} differs from hybrid")

            levels = len(hybrid.dimensions["model_level"])
            shape = (len(hybrid.dimensions["latitude"]), len(hybrid.dimensions["longitude"]))
            if levels != 137 or shape != (33, 41):
                raise ComparisonError(f"unexpected official hybrid grid: levels={levels} shape={shape}")

            generated = []
            for time_index, timestamp in enumerate(times):
                instant = datetime.fromtimestamp(int(timestamp), tz=timezone.utc)
                name = meteorology_name(int(timestamp))
                path = output / name
                messages = []
                with path.open("xb") as stream:
                    for variable, param_id in (("u", 131), ("v", 132), ("w", 135), ("t", 130)):
                        cube = _plain_array(
                            numpy,
                            hybrid.variables[variable],
                            time_index,
                            (137, *shape),
                            f"{variable}[{time_index}]",
                        )
                        for level_index in range(137):
                            messages.append(
                                _write_grib_message(
                                    eccodes,
                                    template,
                                    stream,
                                    cube[level_index],
                                    instant,
                                    param_id=param_id,
                                    level_type="hybrid",
                                    level=level_index + 1,
                                )
                            )

                    logarithm = _plain_array(
                        numpy, lnsp.variables["lnsp"], time_index, shape, f"lnsp[{time_index}]"
                    )
                    messages.append(
                        _write_grib_message(
                            eccodes,
                            template,
                            stream,
                            numpy.exp(logarithm),
                            instant,
                            param_id=134,
                            level_type="surface",
                        )
                    )

                    humidity = _plain_array(
                        numpy,
                        hybrid.variables["q"],
                        time_index,
                        (137, *shape),
                        f"q[{time_index}]",
                    )
                    for level_index in range(137):
                        messages.append(
                            _write_grib_message(
                                eccodes,
                                template,
                                stream,
                                humidity[level_index],
                                instant,
                                param_id=133,
                                level_type="hybrid",
                                level=level_index + 1,
                            )
                        )

                    zeros = numpy.zeros(shape, dtype=numpy.float64)
                    for category_number in ((1, 9), (1, 10)):
                        messages.append(
                            _write_grib_message(
                                eccodes,
                                template,
                                stream,
                                zeros,
                                instant,
                                category_number=category_number,
                                level_type="surface",
                            )
                        )

                    for variable, param_id, level_type, level in (
                        ("u10", 165, "heightAboveGround", 10),
                        ("v10", 166, "heightAboveGround", 10),
                        ("t2m", 167, "heightAboveGround", 2),
                        ("d2m", 168, "heightAboveGround", 2),
                        ("z", 129, "surface", None),
                    ):
                        messages.append(
                            _write_grib_message(
                                eccodes,
                                template,
                                stream,
                                _plain_array(
                                    numpy,
                                    surface.variables[variable],
                                    time_index,
                                    shape,
                                    f"{variable}[{time_index}]",
                                ),
                                instant,
                                param_id=param_id,
                                level_type=level_type,
                                level=level,
                            )
                        )
                if len(messages) != MESSAGES_PER_FRAME:
                    raise ComparisonError(
                        f"generated {len(messages)} messages for {name}, "
                        f"expected {MESSAGES_PER_FRAME}"
                    )
                generated.append(
                    {
                        "name": name,
                        "valid_time_unix": int(timestamp),
                        "size_bytes": path.stat().st_size,
                        "sha256": sha256(path),
                        "message_count": len(messages),
                    }
                )
        finally:
            eccodes.codes_release(template)

    manifest = {
        "schema_version": METEOROLOGY_SCHEMA_VERSION,
        "source_files": list(sources.values()),
        "generated_files": generated,
        "grid": {"nx": 41, "ny": 33, "full_levels": 137},
        "vertical_velocity": {
            "param_id": 135,
            "unit": "Pa/s",
            "conversion": "none",
        },
        "derived_fields": [
            "surface_pressure_pa = exp(log_surface_pressure)",
            "large_scale_precipitation = 0 because wet deposition is disabled",
            "convective_precipitation = 0 because wet deposition and convection are disabled",
        ],
        "toolchain": {
            "eccodes": str(eccodes.codes_get_api_version()),
            "netcdf4_python": str(netcdf4.__version__),
            "numpy": str(numpy.__version__),
        },
    }
    manifest_path = output / "M5_A5_METEOROLOGY.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(manifest_path)
    return 0


def validate_time_contract(time_step_seconds: int, output_interval_seconds: int) -> None:
    if time_step_seconds <= 0 or output_interval_seconds <= 0:
        raise ComparisonError("time step and output interval must be positive")
    if output_interval_seconds % time_step_seconds != 0:
        raise ComparisonError("output interval must be a multiple of the time step")
    if output_interval_seconds < 2 * time_step_seconds:
        raise ComparisonError(
            "FLEXPART output interval must be at least twice the time step"
        )


def command_document(
    *,
    particle_output: bool,
    time_step_seconds: int = 300,
    output_interval_seconds: int = 600,
) -> str:
    validate_time_contract(time_step_seconds, output_interval_seconds)
    return f"""&COMMAND
 LDIRECT=1,
 IBDATE={START_DATE},
 IBTIME={START_TIME},
 IEDATE={END_DATE},
 IETIME={END_TIME},
 LOUTSTEP={output_interval_seconds},
 LOUTAVER={output_interval_seconds},
 LOUTSAMPLE={time_step_seconds},
 LOUTRESTART=-1,
 LSYNCTIME={time_step_seconds},
 CTL=-5.0,
 IFINE=1,
 IOUT=0,
 IPOUT={1 if particle_output else 0},
 LSUBGRID=0,
 LCONVECTION=0,
 LTURBULENCE=0,
 LTURBULENCE_MESO=0,
 LAGESPECTRA=0,
 IPIN=0,
 IOUTPUTFOREACHRELEASE=0,
 IFLUX=0,
 MDOMAINFILL=0,
 IND_SOURCE=1,
 IND_RECEPTOR=1,
 MQUASILAG=0,
 NESTED_OUTPUT=0,
 LNETCDFOUT=1,
 LINIT_COND=0,
 SFC_ONLY=0,
 CBLFLAG=0,
 OHFIELDS_PATH=\"./\",
 NXSHIFT=0,
 MAXTHREADGRID=4,
 MAXFILESIZE=10000,
 LOGVERTINTERP=0,
 /"""


def releases_document(particles: int) -> str:
    if particles <= 0:
        raise ComparisonError("particle count must be positive")
    return f"""&RELEASES_CTRL
 NSPEC=1,
 SPECNUM_REL=24,
 /
&RELEASE
 IDATE1={START_DATE},
 ITIME1={START_TIME},
 IDATE2={START_DATE},
 ITIME2={START_TIME},
 LON1=5.00,
 LON2=5.50,
 LAT1=49.00,
 LAT2=49.50,
 Z1=500.0,
 Z2=1000.0,
 ZKIND=2,
 MASS=1.0,
 PARTS={particles},
 COMMENT=\"M5-A5 comparable release\",
 /"""


def partoptions_document() -> str:
    fields = (
        ("LONGITUDE", True),
        ("LONGITUDE_AVERAGE", False),
        ("LATITUDE", True),
        ("LATITUDE_AVERAGE", False),
        ("HEIGHT", True),
        ("HEIGHT_AVERAGE", False),
        ("PV", False),
        ("PV_AVERAGE", False),
        ("QV", False),
        ("QV_AVERAGE", False),
        ("DENSITY", False),
        ("DENSITY_AVERAGE", False),
        ("TEMPERATURE", False),
        ("TEMPERATURE_AVERAGE", False),
        ("PRESSURE", False),
        ("PRESSURE_AVERAGE", False),
        ("MIXINGHEIGHT", False),
        ("MIXINGHEIGHT_AVERAGE", False),
        ("TROPOPAUSE", False),
        ("TROPOPAUSE_AVERAGE", False),
        ("TOPOGRAPHY", True),
        ("TOPOGRAPHY_AVERAGE", False),
        ("MASS", False),
        ("MASS_AVERAGE", False),
        ("U", False),
        ("U_AVERAGE", False),
        ("V", False),
        ("V_AVERAGE", False),
        ("W", False),
        ("W_AVERAGE", False),
        ("VSETTLING", False),
        ("VSETTLING_AVERAGE", False),
        ("WETDEPOSITION", False),
        ("DRYDEPOSITION", False),
    )
    lines = ["&PARTOPTIONS"]
    lines.extend(f" {name}={'.true.' if enabled else '.false.'}," for name, enabled in fields)
    lines.append(" /")
    return "\n".join(lines)


def available_document() -> str:
    lines = [
        "XXXXXX EMPTY LINES XXXXXXXXX",
        "XXXXXX EMPTY LINES XXXXXXXX",
        "YYYYMMDD HHMMSS   name of the file(up to 80 characters)",
    ]
    for name in METEOROLOGY_NAMES:
        hour = name[-2:]
        lines.append(f"20181201 {hour}0000      {name}      ON DISK")
    return "\n".join(lines)


def pathnames_document(options: Path, output: Path, meteorology: Path, available: Path) -> str:
    def directory(path: Path) -> str:
        value = str(path.resolve())
        return value if value.endswith("/") else value + "/"

    return "\n".join(
        (directory(options), directory(output), directory(meteorology), str(available.resolve()))
    )


def validate_meteorology(root: Path) -> list[dict[str, object]]:
    manifest_path = root / "M5_A5_METEOROLOGY.json"
    if not manifest_path.is_file():
        raise ComparisonError(f"staged meteorology manifest missing: {manifest_path}")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if manifest.get("schema_version") != METEOROLOGY_SCHEMA_VERSION:
        raise ComparisonError("staged meteorology schema identity mismatch")
    records = manifest.get("generated_files")
    if not isinstance(records, list) or [record.get("name") for record in records] != list(
        METEOROLOGY_NAMES
    ):
        raise ComparisonError("staged meteorology inventory mismatch")

    identities = []
    for record in records:
        name = str(record["name"])
        source = root / name
        if not source.is_file():
            raise ComparisonError(f"required meteorology missing: {source}")
        actual = sha256(source)
        if actual != record.get("sha256"):
            raise ComparisonError(f"meteorology identity mismatch for {name}: {actual}")
        if source.stat().st_size != record.get("size_bytes"):
            raise ComparisonError(f"meteorology size mismatch for {name}")
        identities.append({"name": name, "size_bytes": source.stat().st_size, "sha256": actual})
    return identities


def write_json(path: Path, value: object) -> None:
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def validate_trajecta_data(root: Path) -> list[dict[str, object]]:
    identities = []
    for name, expected in TRAJECTA_DATA_IDENTITIES.items():
        path = root / name
        identity = require_sha256(path, expected)
        identity["path"] = name
        identities.append(identity)
    return identities


def trajecta_case_document(
    particles: int,
    time_step_seconds: int = 300,
    output_interval_seconds: int = 600,
) -> dict[str, object]:
    if particles <= 0:
        raise ComparisonError("particle count must be positive")
    validate_time_contract(time_step_seconds, output_interval_seconds)
    return {
        "schema_version": 0,
        "kind": "case",
        "metadata": {"name": f"m5-a5-flexpart-comparison-p{particles}"},
        "time": {
            "start": {"seconds_since_unix_epoch": START_UNIX, "nanosecond": 0},
            "end": {"seconds_since_unix_epoch": END_UNIX, "nanosecond": 0},
            "direction": "forward",
        },
        "meteorology": {
            "domains": [
                {
                    "id": "limited",
                    "dataset": "era5-hybrid",
                    "priority": 1,
                    "horizontal_halo_cells": 1,
                }
            ]
        },
        "particle_population": {
            "strategy": "release_driven",
            "id": "release",
            "events": [
                {
                    "id": "event",
                    "start": {
                        "seconds_since_unix_epoch": START_UNIX,
                        "nanosecond": 0,
                    },
                    "end": {
                        "seconds_since_unix_epoch": START_UNIX,
                        "nanosecond": 0,
                    },
                    "particle_count": particles,
                    "mass": {"tracer": {"value": 1, "unit": "kg"}},
                    "geometry": {
                        "source": "inline",
                        "geometry": {
                            "type": "Polygon",
                            "coordinates": [
                                [
                                    [5.0, 49.0],
                                    [5.5, 49.0],
                                    [5.5, 49.5],
                                    [5.0, 49.5],
                                    [5.0, 49.0],
                                ]
                            ],
                        },
                    },
                    "vertical": {
                        "coordinate": "above_sea_level",
                        "lower": {"value": 500, "unit": "m"},
                        "upper": {"value": 1_000, "unit": "m"},
                    },
                }
            ],
        },
        "substances": [{"id": "tracer", "display_name": "Tracer"}],
        "numerics": {
            "time_step": {"value": time_step_seconds, "unit": "s"},
            "integrator": {"model": "rk2_spherical/v0"},
            "boundaries": {
                "policies": [
                    "surface_reflect/v0",
                    "model_top_terminate/v0",
                    "limited_domain_terminate/v0",
                ]
            },
            "random_seed": 5_205,
        },
        "outputs": [
            {
                "product": "particle_state/v1",
                "schedule": {
                    "mode": "interval",
                    "interval": {"value": output_interval_seconds, "unit": "s"},
                },
                "sink": {"model": "particle_state_sqlite/v1"},
            }
        ],
    }


def trajecta_profile_document() -> dict[str, object]:
    return {
        "schema_version": 0,
        "kind": "run_profile",
        "metadata": {"name": "product"},
        "case_path": "../cases/comparison.json",
        "output_root": "../runs",
        "datasets": [
            {
                "dataset": "era5-hybrid",
                "lockfile": "../locks/era5-hybrid-rust.lock.json",
                "data_roots": {"met": "../data"},
                "reader_backend": "rust",
            }
        ],
        "execution": {
            "worker_threads": 4,
            "memory_budget_bytes": 2_147_483_648,
            "executor": "cpu",
            "meteorology_reader": "rust",
        },
    }


def trajecta_project_document() -> dict[str, object]:
    return {
        "schema_version": "trajecta.project-index/v1",
        "name": "m5-a5-flexpart-comparison",
        "cases": {"comparison": "cases/comparison.json"},
        "profiles": {
            "product": {
                "path": "profiles/product.json",
                "dataset_profiles": {
                    "era5-hybrid": "era5-cds-hybrid137-v0",
                },
            }
        },
        "default_profile": "product",
    }


def prepare_trajecta(arguments: argparse.Namespace) -> int:
    root = arguments.output.resolve()
    if root.exists():
        raise ComparisonError(f"refusing to overwrite Trajecta case: {root}")
    data_root = arguments.data.resolve()
    identities = validate_trajecta_data(data_root)
    project_root = root / "project"
    for directory in ("cases", "profiles", "locks", "runs", "data"):
        (project_root / directory).mkdir(parents=True, exist_ok=False)
    for identity in identities:
        source = data_root / str(identity["path"])
        shutil.copy2(source, project_root / "data" / source.name)
    write_json(
        project_root / "cases" / "comparison.json",
        trajecta_case_document(
            arguments.particles,
            arguments.time_step_seconds,
            arguments.output_interval_seconds,
        ),
    )
    write_json(project_root / "profiles" / "product.json", trajecta_profile_document())
    write_json(project_root / "trajecta-project.yaml", trajecta_project_document())
    manifest = {
        "schema_version": TRAJECTA_CASE_SCHEMA_VERSION,
        "particles": arguments.particles,
        "worker_threads": 4,
        "start_utc": "2018-12-01T03:00:00Z",
        "end_utc": "2018-12-01T04:00:00Z",
        "time_step_seconds": arguments.time_step_seconds,
        "output_interval_seconds": arguments.output_interval_seconds,
        "dataset_profile": "era5-cds-hybrid137-v0",
        "reader_backend": "rust",
        "data": identities,
        "files": {},
    }
    for path in sorted(project_root.rglob("*")):
        if path.is_file():
            manifest["files"][path.relative_to(root).as_posix()] = {
                "size_bytes": path.stat().st_size,
                "sha256": sha256(path),
            }
    manifest_path = root / "M5_A5_TRAJECTA_CASE.json"
    write_json(manifest_path, manifest)
    print(manifest_path)
    return 0


def _array_comparison(numpy, left, right) -> dict[str, object]:
    left_array = numpy.asarray(left)
    right_array = numpy.asarray(right)
    if left_array.shape != right_array.shape:
        return {
            "passed": False,
            "left_shape": list(left_array.shape),
            "right_shape": list(right_array.shape),
            "value_count": 0,
            "maximum_absolute_error": None,
        }
    difference = numpy.abs(left_array.astype(numpy.float64) - right_array.astype(numpy.float64))
    maximum = float(difference.max()) if difference.size else 0.0
    return {
        "passed": bool(numpy.array_equal(left_array, right_array)),
        "left_shape": list(left_array.shape),
        "right_shape": list(right_array.shape),
        "value_count": int(left_array.size),
        "maximum_absolute_error": maximum,
    }


def _packing_comparison(numpy, expected, actual, packing_error: float) -> dict[str, object]:
    expected_array = numpy.asarray(expected, dtype=numpy.float64).reshape(-1)
    actual_array = numpy.asarray(actual, dtype=numpy.float64).reshape(-1)
    if expected_array.shape != actual_array.shape:
        return {
            "passed": False,
            "value_count": 0,
            "maximum_absolute_error": None,
            "packing_error": packing_error,
            "tolerance": None,
        }
    difference = numpy.abs(expected_array - actual_array)
    maximum = float(difference.max()) if difference.size else 0.0
    scale = float(numpy.max(numpy.abs(expected_array))) if expected_array.size else 1.0
    roundoff = float(numpy.finfo(numpy.float64).eps * max(1.0, scale) * 8.0)
    tolerance = packing_error + roundoff
    return {
        "passed": bool(numpy.isfinite(actual_array).all() and maximum <= tolerance),
        "value_count": int(expected_array.size),
        "maximum_absolute_error": maximum,
        "packing_error": packing_error,
        "tolerance": tolerance,
    }


def audit_meteorology(arguments: argparse.Namespace) -> int:
    output = arguments.output.resolve()
    if output.exists():
        raise ComparisonError(f"refusing to overwrite meteorology audit: {output}")
    source_root = arguments.source.resolve()
    ready_root = arguments.trajecta_data.resolve()
    staged_root = arguments.meteorology.resolve()
    common_sources = {
        relative: require_sha256(source_root / relative, expected)
        for relative, expected in SOURCE_IDENTITIES.items()
    }
    trajecta_only_sources = {
        relative: require_sha256(source_root / relative, expected)
        for relative, expected in TRAJECTA_ONLY_SOURCE_IDENTITIES.items()
    }
    ready_identities = validate_trajecta_data(ready_root)
    staged_identities = validate_meteorology(staged_root)
    eccodes, netcdf4, numpy = _stage_modules()

    ready_checks: dict[str, dict[str, object]] = {}
    hybrid_path = source_root / "raw/era5_hybrid137_20181201.nc"
    lnsp_path = source_root / "raw/era5_lnsp_20181201.nc"
    surface_path = source_root / "raw/era5_hybrid_surface_base_20181201.nc"
    flux_path = source_root / "raw/era5_hybrid_surface_flux_20181201.nc"
    probe_path = source_root / "raw/era5_hybrid_pv_probe.grib"
    ready_hybrid_path = ready_root / "era5_hybrid137_prepared_20181201.nc"
    ready_surface_path = ready_root / "era5_surface_20181201.nc"
    with (
        netcdf4.Dataset(hybrid_path.as_posix()) as raw_hybrid,
        netcdf4.Dataset(lnsp_path.as_posix()) as raw_lnsp,
        netcdf4.Dataset(surface_path.as_posix()) as raw_surface,
        netcdf4.Dataset(flux_path.as_posix()) as raw_flux,
        netcdf4.Dataset(ready_hybrid_path.as_posix()) as ready_hybrid,
        netcdf4.Dataset(ready_surface_path.as_posix()) as ready_surface,
        probe_path.open("rb") as probe_stream,
    ):
        for name in ("valid_time", "latitude", "longitude"):
            ready_checks[f"hybrid.{name}"] = _array_comparison(
                numpy, raw_hybrid.variables[name][:], ready_hybrid.variables[name][:]
            )
        ready_checks["hybrid.model_level"] = _array_comparison(
            numpy, raw_hybrid.variables["model_level"][:], ready_hybrid.variables["hybrid"][:]
        )
        for name in ("t", "u", "v", "q", "w"):
            ready_checks[f"hybrid.{name}"] = _array_comparison(
                numpy, raw_hybrid.variables[name][:], ready_hybrid.variables[name][:]
            )
        raw_lnsp_values = numpy.asarray(raw_lnsp.variables["lnsp"][:, 0, :, :])
        ready_checks["hybrid.lnsp"] = _array_comparison(
            numpy, raw_lnsp_values.astype(numpy.float64), ready_hybrid.variables["lnsp"][:]
        )
        ready_checks["hybrid.sp"] = _array_comparison(
            numpy,
            numpy.exp(raw_lnsp_values.astype(numpy.float64)),
            ready_hybrid.variables["sp"][:],
        )
        sp_scale = float(numpy.max(numpy.abs(ready_hybrid.variables["sp"][:])))
        sp_roundoff = float(numpy.spacing(sp_scale) * 2.0)
        ready_checks["hybrid.sp"]["passed"] = bool(
            float(ready_checks["hybrid.sp"]["maximum_absolute_error"]) <= sp_roundoff
        )
        ready_checks["hybrid.sp"]["roundoff_tolerance"] = sp_roundoff
        ready_checks["hybrid.sp"]["classification"] = "aligned-derived"
        probe = eccodes.codes_grib_new_from_file(probe_stream)
        if probe is None:
            raise ComparisonError("official PV probe contains no GRIB message")
        try:
            pv = numpy.asarray(eccodes.codes_get_array(probe, "pv"), dtype=numpy.float64)
        finally:
            eccodes.codes_release(probe)
        ready_checks["hybrid.ap"] = _array_comparison(
            numpy, pv[:138], ready_hybrid.variables["ap"][:]
        )
        ready_checks["hybrid.b"] = _array_comparison(
            numpy, pv[138:], ready_hybrid.variables["b"][:]
        )
        for name in ("valid_time", "latitude", "longitude", "z", "u10", "v10", "t2m", "d2m", "fsr", "blh", "zust"):
            ready_checks[f"surface.{name}"] = _array_comparison(
                numpy, raw_surface.variables[name][:], ready_surface.variables[name][:]
            )
        for name in ("ishf", "ie"):
            ready_checks[f"surface.{name}"] = _array_comparison(
                numpy, raw_flux.variables[name][:], ready_surface.variables[name][:]
            )

        raw_times = numpy.asarray(raw_hybrid.variables["valid_time"][:], dtype=numpy.int64)
        expected_names = tuple(meteorology_name(int(value)) for value in raw_times)
        if expected_names != METEOROLOGY_NAMES:
            raise ComparisonError("raw four-frame times drifted")
        grib_fields: dict[str, dict[str, object]] = {}

        def record_field(label: str, result: dict[str, object]) -> None:
            aggregate = grib_fields.setdefault(
                label,
                {
                    "passed": True,
                    "message_count": 0,
                    "value_count": 0,
                    "maximum_absolute_error": 0.0,
                    "maximum_packing_error": 0.0,
                    "worst_message": None,
                },
            )
            aggregate["message_count"] = int(aggregate["message_count"]) + 1
            aggregate["value_count"] = int(aggregate["value_count"]) + int(
                result["value_count"]
            )
            aggregate["maximum_packing_error"] = max(
                float(aggregate["maximum_packing_error"]), float(result["packing_error"])
            )
            error = result["maximum_absolute_error"]
            if error is not None and float(error) >= float(aggregate["maximum_absolute_error"]):
                aggregate["maximum_absolute_error"] = float(error)
                aggregate["worst_message"] = result["message"]
            aggregate["passed"] = bool(aggregate["passed"] and result["passed"])

        for time_index, name in enumerate(METEOROLOGY_NAMES):
            path = staged_root / name
            with path.open("rb") as stream:
                def compare_next(
                    label: str,
                    expected,
                    *,
                    param_id: int | None,
                    category_number: tuple[int, int] | None,
                    level_type: str,
                    level: int,
                ) -> None:
                    message = eccodes.codes_grib_new_from_file(stream)
                    if message is None:
                        raise ComparisonError(f"staged GRIB ended early at {name} {label}")
                    try:
                        actual_param = int(eccodes.codes_get(message, "paramId"))
                        actual_category = int(eccodes.codes_get(message, "parameterCategory"))
                        actual_number = int(eccodes.codes_get(message, "parameterNumber"))
                        actual_type = str(eccodes.codes_get(message, "typeOfLevel"))
                        actual_level = int(eccodes.codes_get(message, "level"))
                        identity_ok = (
                            (param_id is None or actual_param == param_id)
                            and (
                                category_number is None
                                or (actual_category, actual_number) == category_number
                            )
                            and actual_type == level_type
                            and actual_level == level
                            and int(eccodes.codes_get(message, "NV")) == 276
                            and int(eccodes.codes_get(message, "Ni")) == 41
                            and int(eccodes.codes_get(message, "Nj")) == 33
                        )
                        result = _packing_comparison(
                            numpy,
                            expected,
                            eccodes.codes_get_values(message),
                            float(eccodes.codes_get(message, "packingError")),
                        )
                        result["passed"] = bool(result["passed"] and identity_ok)
                        result["message"] = f"{name}:{actual_param}:{actual_type}:{actual_level}"
                        record_field(label, result)
                    finally:
                        eccodes.codes_release(message)

                for variable, param_id in (("u", 131), ("v", 132), ("w", 135), ("t", 130)):
                    cube = numpy.asarray(raw_hybrid.variables[variable][time_index])
                    for level_index in range(137):
                        compare_next(
                            variable,
                            cube[level_index],
                            param_id=param_id,
                            category_number=None,
                            level_type="hybrid",
                            level=level_index + 1,
                        )
                compare_next(
                    "sp",
                    numpy.exp(numpy.asarray(raw_lnsp.variables["lnsp"][time_index, 0], dtype=numpy.float64)),
                    param_id=134,
                    category_number=None,
                    level_type="surface",
                    level=0,
                )
                humidity = numpy.asarray(raw_hybrid.variables["q"][time_index])
                for level_index in range(137):
                    compare_next(
                        "q",
                        humidity[level_index],
                        param_id=133,
                        category_number=None,
                        level_type="hybrid",
                        level=level_index + 1,
                    )
                zeros = numpy.zeros((33, 41), dtype=numpy.float64)
                for label, category_number in (
                    ("large_scale_precipitation_disabled", (1, 9)),
                    ("convective_precipitation_disabled", (1, 10)),
                ):
                    compare_next(
                        label,
                        zeros,
                        param_id=None,
                        category_number=category_number,
                        level_type="surface",
                        level=0,
                    )
                for variable, param_id, level_type, level in (
                    ("u10", 165, "heightAboveGround", 10),
                    ("v10", 166, "heightAboveGround", 10),
                    ("t2m", 167, "heightAboveGround", 2),
                    ("d2m", 168, "heightAboveGround", 2),
                    ("z", 129, "surface", 0),
                ):
                    compare_next(
                        variable,
                        raw_surface.variables[variable][time_index],
                        param_id=param_id,
                        category_number=None,
                        level_type=level_type,
                        level=level,
                    )
                extra = eccodes.codes_grib_new_from_file(stream)
                if extra is not None:
                    eccodes.codes_release(extra)
                    raise ComparisonError(f"staged GRIB has extra messages in {name}")

    ready_passed = all(check["passed"] for check in ready_checks.values())
    grib_passed = all(check["passed"] for check in grib_fields.values())
    value = {
        "schema_version": "trajecta.m5-a5-meteorology-equivalence/v1",
        "status": "passed" if ready_passed and grib_passed else "failed",
        "source_identities": {
            "common": list(common_sources.values()),
            "trajecta_only": list(trajecta_only_sources.values()),
        },
        "trajecta_ready_identities": ready_identities,
        "flexpart_staged_identities": staged_identities,
        "trajecta_ready_exact_checks": ready_checks,
        "flexpart_grib_packing_checks": grib_fields,
        "classifications": {
            "common_source_fields": "exact",
            "trajecta_ready_common_fields": "exact",
            "flexpart_grib_common_fields": "aligned",
            "disabled_precipitation_compatibility_fields": "not-comparable",
            "trajecta_surface_flux_fields": "not-comparable",
        },
        "notes": [
            "FLEXPART GRIB values must stay within each message's ecCodes packingError.",
            "The two zero precipitation messages satisfy FLEXPART input structure only; wet deposition and convection are disabled.",
            "Trajecta surface flux fields remain official source values but are outside the advection-only comparison quantity set.",
        ],
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    write_json(output, value)
    print(output)
    return 0 if value["status"] == "passed" else 1


def prepare(arguments: argparse.Namespace) -> int:
    root = arguments.output.resolve()
    if root.exists():
        raise ComparisonError(f"refusing to overwrite comparison case: {root}")
    source_options = arguments.flexpart_options.resolve()
    source_met = arguments.meteorology.resolve()
    identities = validate_meteorology(source_met)

    options = root / "options"
    output = root / "output"
    meteorology = root / "meteorology"
    options.mkdir(parents=True)
    output.mkdir()
    meteorology.mkdir()
    (options / "SPECIES").mkdir()

    for name in STATIC_OPTION_FILES:
        source = source_options / name
        if not source.is_file():
            raise ComparisonError(f"required FLEXPART option missing: {source}")
        shutil.copy2(source, options / name)
    species = arguments.species_file.resolve()
    if not species.is_file():
        raise ComparisonError(f"required FLEXPART species missing: {species}")
    shutil.copy2(species, options / "SPECIES" / "SPECIES_024")
    for identity in identities:
        name = str(identity["name"])
        shutil.copy2(source_met / name, meteorology / name)
    shutil.copy2(source_met / "M5_A5_METEOROLOGY.json", meteorology)

    write_text(
        options / "COMMAND",
        command_document(
            particle_output=arguments.mode == "product",
            time_step_seconds=arguments.time_step_seconds,
            output_interval_seconds=arguments.output_interval_seconds,
        ),
    )
    write_text(options / "RELEASES", releases_document(arguments.particles))
    write_text(options / "PARTOPTIONS", partoptions_document())
    available = root / "AVAILABLE"
    pathnames = root / "pathnames"
    write_text(available, available_document())
    write_text(pathnames, pathnames_document(options, output, meteorology, available))

    manifest = {
        "schema_version": SCHEMA_VERSION,
        "mode": arguments.mode,
        "particles": arguments.particles,
        "worker_threads": 4,
        "start_utc": "2018-12-01T03:00:00Z",
        "end_utc": "2018-12-01T04:00:00Z",
        "time_step_seconds": arguments.time_step_seconds,
        "output_interval_seconds": arguments.output_interval_seconds,
        "meteorology": identities,
        "meteorology_manifest_sha256": sha256(source_met / "M5_A5_METEOROLOGY.json"),
        "files": {},
    }
    for path in sorted(root.rglob("*")):
        if path.is_file() and path.name != "M5_A5_FLEXPART_CASE.json":
            manifest["files"][path.relative_to(root).as_posix()] = {
                "size_bytes": path.stat().st_size,
                "sha256": sha256(path),
            }
    manifest_path = root / "M5_A5_FLEXPART_CASE.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(manifest_path)
    return 0


def parse_elapsed_seconds(value: str) -> float:
    parts = value.strip().split(":")
    try:
        numbers = [float(part) for part in parts]
    except ValueError as error:
        raise ComparisonError(f"invalid /usr/bin/time elapsed value: {value}") from error
    if len(numbers) == 2:
        minutes, seconds = numbers
        return minutes * 60.0 + seconds
    if len(numbers) == 3:
        hours, minutes, seconds = numbers
        return hours * 3600.0 + minutes * 60.0 + seconds
    raise ComparisonError(f"invalid /usr/bin/time elapsed value: {value}")


def parse_time_verbose(stderr: str) -> dict[str, object]:
    fields = {
        "User time (seconds)": "user_seconds",
        "System time (seconds)": "system_seconds",
        "Elapsed (wall clock) time (h:mm:ss or m:ss)": "elapsed_seconds",
        "Maximum resident set size (kbytes)": "peak_rss_kib",
        "File system inputs": "filesystem_inputs",
        "File system outputs": "filesystem_outputs",
        "Exit status": "reported_exit_status",
    }
    result: dict[str, object] = {}
    for line in stderr.splitlines():
        stripped = line.strip()
        for source, target in fields.items():
            prefix = source + ":"
            if not stripped.startswith(prefix):
                continue
            value = stripped[len(prefix) :].strip()
            if target == "elapsed_seconds":
                result[target] = parse_elapsed_seconds(value)
            elif target.endswith("_seconds"):
                result[target] = float(value)
            else:
                result[target] = int(value)
            break
    missing = set(fields.values()) - set(result)
    if missing:
        raise ComparisonError(f"incomplete /usr/bin/time -v output: {sorted(missing)}")
    return result


def split_application_stderr(stderr: str) -> tuple[str, str]:
    lines = stderr.splitlines()
    for index, line in enumerate(lines):
        if line.strip().startswith("Command being timed:"):
            return "\n".join(lines[:index]).strip(), "\n".join(lines[index:])
    raise ComparisonError("/usr/bin/time -v output has no command boundary")


def performance_evidence(path: Path, *, required: bool) -> dict[str, object] | None:
    if not path.is_file():
        if required:
            raise ComparisonError(f"required performance attribution missing: {path}")
        return None
    value = json.loads(path.read_text(encoding="utf-8"))
    if value.get("schema_version") != "trajecta.performance-attribution/v1":
        raise ComparisonError("performance attribution schema identity mismatch")
    stages = value.get("stages")
    if not isinstance(stages, dict):
        raise ComparisonError("performance attribution stages are missing")
    runner_total = stages.get("runner_total")
    runner_output = stages.get("runner_output")
    if not isinstance(runner_total, dict) or not isinstance(runner_output, dict):
        raise ComparisonError("performance attribution omits runner total/output")
    total = runner_total.get("total")
    output = runner_output.get("total")
    if (
        runner_total.get("observations") != 1
        or not isinstance(total, int)
        or not isinstance(output, int)
        or total <= 0
        or output < 0
        or output > total
    ):
        raise ComparisonError("performance attribution runner totals are invalid")
    peak_rss = value.get("process_peak_rss_bytes")
    if required and (not isinstance(peak_rss, int) or peak_rss <= 0):
        raise ComparisonError("performance attribution omits worker peak RSS")
    return {
        "path": str(path),
        "sha256": sha256(path),
        "runner_total_nanoseconds": total,
        "runner_output_nanoseconds": output,
        "equivalent_core_nanoseconds": total - output,
        "process_peak_rss_bytes": peak_rss,
    }


def run_trajecta(arguments: argparse.Namespace) -> int:
    root = arguments.case.resolve()
    case_manifest = root / "M5_A5_TRAJECTA_CASE.json"
    result_path = root / "M5_A5_TRAJECTA_RUN.json"
    if not case_manifest.is_file():
        raise ComparisonError(f"prepared Trajecta case missing: {case_manifest}")
    if result_path.exists():
        raise ComparisonError(f"refusing to overwrite Trajecta run evidence: {result_path}")
    prepared = json.loads(case_manifest.read_text(encoding="utf-8"))
    if prepared.get("schema_version") != TRAJECTA_CASE_SCHEMA_VERSION:
        raise ComparisonError("prepared Trajecta case schema identity mismatch")

    checks = {
        name: False
        for name in (
            "package_identity",
            "project_finalized",
            "run_complete",
            "manifest_complete",
            "abnormal_zero",
            "particle_count",
            "output_schedule",
            "lifecycle",
            "quality",
            "mass_ledger",
            "sqlite_integrity",
            "terminal_wal",
            "full_verify",
            "performance_attribution",
            "daemon_idle",
        )
    }
    failures: list[str] = []
    run: dict[str, object] = {}
    config = root / "config.toml"
    recorder = None
    try:
        identity = product.validate_product_root(arguments.package_root)
        checks["package_identity"] = True
        recorder = product.CommandRecorder(identity, root, arguments.timeout_seconds)
        performance_path = root / "performance-attribution.json"
        recorder.environment["TRAJECTA_PERFORMANCE_ATTRIBUTION_PATH"] = str(performance_path)
        product.configure_runtime(recorder, config)
        project_root = root / "project"
        finalized = recorder.json(
            "project-finalize",
            ["project", "finalize"],
            config=config,
            project=project_root,
        )
        checks["project_finalized"] = finalized.get("data", {}).get("state") == "finalized"

        cli_arguments = [
            "--format",
            "json",
            "--config",
            str(config),
            "--project",
            str(project_root),
            "run",
            "--profile",
            "product",
        ]
        command = [
            "taskset",
            "-c",
            arguments.cpu_set,
            "/usr/bin/time",
            "-v",
            str(identity.binary),
            *cli_arguments,
        ]
        started = time.monotonic_ns()
        try:
            completed = subprocess.run(
                command,
                cwd=root,
                env=recorder.environment,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                timeout=arguments.timeout_seconds,
                check=False,
            )
            timed_out = False
        except subprocess.TimeoutExpired as error:
            completed = subprocess.CompletedProcess(
                command,
                124,
                stdout=error.stdout or b"",
                stderr=error.stderr or b"",
            )
            timed_out = True
        wall_nanoseconds = time.monotonic_ns() - started
        stdout_path = root / "trajecta.stdout.log"
        stderr_path = root / "trajecta.stderr.log"
        stdout_path.write_bytes(completed.stdout)
        stderr_path.write_bytes(completed.stderr)
        if timed_out:
            raise ComparisonError("Trajecta foreground run timed out")
        stderr = completed.stderr.decode("utf-8", errors="replace")
        application_stderr, time_stderr = split_application_stderr(stderr)
        if application_stderr:
            raise ComparisonError("successful Trajecta machine run wrote application stderr")
        time_verbose = parse_time_verbose(time_stderr)
        try:
            envelope = json.loads(completed.stdout)
        except (UnicodeDecodeError, json.JSONDecodeError) as error:
            raise ComparisonError("Trajecta foreground run returned invalid JSON") from error
        if completed.returncode != 0:
            raise ComparisonError(f"Trajecta foreground run exited {completed.returncode}")
        data = envelope.get("data")
        checks["run_complete"] = (
            envelope.get("ok") is True
            and envelope.get("run_success") is True
            and isinstance(data, dict)
            and data.get("state") == "complete"
        )
        if not isinstance(data, dict):
            raise ComparisonError("Trajecta run envelope has no data object")
        output_text = data.get("output_directory")
        series = data.get("job_series_id")
        if not isinstance(output_text, str) or not isinstance(series, str):
            raise ComparisonError("Trajecta run envelope omits output/job identity")
        output_directory = Path(output_text)
        manifest_path = output_directory / "run-manifest.json"
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        checks["manifest_complete"] = manifest.get("status") == "complete"
        checks["abnormal_zero"] = manifest.get("terminations", {}).get("abnormal_count") == 0

        inspection_envelope = recorder.json(
            "result-inspect",
            ["result", "inspect", str(output_directory)],
            config=config,
        )
        inspection = inspection_envelope.get("data", {})
        checks["particle_count"] = (
            inspection.get("particles", {}).get("particle_count") == prepared.get("particles")
        )
        checks["lifecycle"] = inspection.get("lifecycle", {}).get("status") == "complete"
        checks["quality"] = product.quality_is_valid(
            inspection.get("quality"), inspection.get("particles")
        )
        checks["mass_ledger"] = product.mass_ledger_is_valid(manifest, inspection)

        sqlite_path = output_directory / manifest.get("sqlite", {}).get(
            "relative_path", "particles.sqlite"
        )
        sqlite_ok, _particle_id = product.sqlite_audit(
            sqlite_path, manifest.get("sqlite", {}).get("row_counts", {})
        )
        checks["sqlite_integrity"] = sqlite_ok
        wal = sqlite_path.with_name(sqlite_path.name + "-wal")
        checks["terminal_wal"] = not wal.exists() or wal.stat().st_size == 0
        with sqlite3.connect(os.fspath(sqlite_path)) as connection:
            event_times = [
                int(row[0])
                for row in connection.execute(
                    "SELECT physical_seconds FROM output_event ORDER BY event_sequence"
                )
            ]
        output_interval_seconds = int(prepared["output_interval_seconds"])
        checks["output_schedule"] = event_times == list(
            range(START_UNIX, END_UNIX + 1, output_interval_seconds)
        )

        verification = recorder.json(
            "result-verify-full",
            ["result", "verify", series, "--full"],
            config=config,
        ).get("data", {})
        checks["full_verify"] = (
            verification.get("status") == "complete"
            and verification.get("run_success") is True
        )
        attribution = performance_evidence(
            performance_path, required=arguments.require_performance
        )
        checks["performance_attribution"] = attribution is not None or not arguments.require_performance
        runner_milliseconds = (
            product.timestamp_ns(manifest["finished_at"])
            - product.timestamp_ns(manifest["started_at"])
        ) // 1_000_000
        run = {
            "package": {
                "root": str(identity.package_root),
                "source_tree_sha256": identity.source_tree_sha256,
                "build_manifest_sha256": identity.build_manifest_sha256,
                "binary_sha256": identity.binary_sha256,
            },
            "command": command,
            "cpu_set": arguments.cpu_set,
            "exit_code": completed.returncode,
            "wall_nanoseconds": wall_nanoseconds,
            "time_verbose": time_verbose,
            "runner_milliseconds": runner_milliseconds,
            "job_series_id": series,
            "run_id": data.get("run_id"),
            "output_directory": str(output_directory),
            "manifest_sha256": sha256(manifest_path),
            "sqlite_sha256": sha256(sqlite_path),
            "performance_attribution": attribution,
            "stdout_sha256": sha256(stdout_path),
            "stderr_sha256": sha256(stderr_path),
        }
    except (
        ComparisonError,
        product.CommandFailure,
        product.ProductError,
        OSError,
        sqlite3.Error,
        KeyError,
        TypeError,
        ValueError,
    ) as error:
        failures.append(str(error))
    checks["daemon_idle"] = product.wait_for_idle(config) if config.exists() else True
    failures.extend(
        f"check failed: {name}" for name, passed in checks.items() if not passed
    )
    value = {
        "schema_version": "trajecta.m5-a5-trajecta-run/v1",
        "case_manifest_sha256": sha256(case_manifest),
        "checks": checks,
        "failures": failures,
        "run": run,
        "status": "passed" if not failures else "failed",
    }
    write_json(result_path, value)
    print(result_path)
    return 0 if not failures else 1


EARTH_MEAN_RADIUS_M = 6_371_008.8


def _great_circle_distance(numpy, lon1, lat1, lon2, lat2):
    lon1_r = numpy.radians(lon1)
    lat1_r = numpy.radians(lat1)
    lon2_r = numpy.radians(lon2)
    lat2_r = numpy.radians(lat2)
    delta_lon = lon2_r - lon1_r
    delta_lat = lat2_r - lat1_r
    haversine = (
        numpy.sin(delta_lat / 2.0) ** 2
        + numpy.cos(lat1_r) * numpy.cos(lat2_r) * numpy.sin(delta_lon / 2.0) ** 2
    )
    return 2.0 * EARTH_MEAN_RADIUS_M * numpy.arcsin(numpy.sqrt(numpy.clip(haversine, 0, 1)))


def _ensemble_metrics(numpy, longitude, latitude, height) -> dict[str, object]:
    longitude = numpy.asarray(longitude, dtype=numpy.float64).reshape(-1)
    latitude = numpy.asarray(latitude, dtype=numpy.float64).reshape(-1)
    height = numpy.asarray(height, dtype=numpy.float64).reshape(-1)
    finite = numpy.isfinite(longitude) & numpy.isfinite(latitude) & numpy.isfinite(height)
    finite_count = int(finite.sum())
    if finite_count == 0:
        raise ComparisonError("scientific output contains no finite active particles")
    lon = longitude[finite]
    lat = latitude[finite]
    z = height[finite]
    lon_r = numpy.radians(lon)
    lat_r = numpy.radians(lat)
    x = numpy.mean(numpy.cos(lat_r) * numpy.cos(lon_r))
    y = numpy.mean(numpy.cos(lat_r) * numpy.sin(lon_r))
    vertical = numpy.mean(numpy.sin(lat_r))
    centroid_lon = float(numpy.degrees(numpy.arctan2(y, x)))
    centroid_lat = float(numpy.degrees(numpy.arctan2(vertical, numpy.hypot(x, y))))
    source_distance = float(
        _great_circle_distance(numpy, 5.25, 49.25, centroid_lon, centroid_lat)
    )
    dispersion = _great_circle_distance(numpy, centroid_lon, centroid_lat, lon, lat)
    longitude_cell = numpy.floor((numpy.mod(lon + 180.0, 360.0)) / 0.1).astype(numpy.int64)
    latitude_cell = numpy.floor((lat + 90.0) / 0.1).astype(numpy.int64)
    height_cell = numpy.floor(z / 250.0).astype(numpy.int64)
    occupied = len(set(zip(longitude_cell.tolist(), latitude_cell.tolist(), height_cell.tolist())))
    return {
        "coordinate_count": int(longitude.size),
        "finite_count": finite_count,
        "nonfinite_count": int(longitude.size - finite_count),
        "centroid_longitude_degrees": centroid_lon,
        "centroid_latitude_degrees": centroid_lat,
        "centroid_height_asl_m": float(numpy.mean(z)),
        "centroid_distance_from_source_m": source_distance,
        "rms_horizontal_dispersion_m": float(numpy.sqrt(numpy.mean(dispersion ** 2))),
        "height_asl_mean_m": float(numpy.mean(z)),
        "height_asl_standard_deviation_m": float(numpy.std(z)),
        "occupied_audit_cells": occupied,
        "audit_grid": {
            "longitude_degrees": 0.1,
            "latitude_degrees": 0.1,
            "height_m": 250,
        },
    }


def _masked_to_nan(numpy, values):
    if numpy.ma.isMaskedArray(values):
        return numpy.asarray(values.filled(numpy.nan), dtype=numpy.float64)
    return numpy.asarray(values, dtype=numpy.float64)


def scientific_comparison(arguments: argparse.Namespace) -> int:
    output = arguments.output.resolve()
    if output.exists():
        raise ComparisonError(f"refusing to overwrite scientific comparison: {output}")
    flexpart_case = arguments.flexpart_case.resolve()
    trajecta_run_path = arguments.trajecta_run.resolve()
    flexpart_result = json.loads(
        (flexpart_case / "M5_A5_FLEXPART_RUN.json").read_text(encoding="utf-8")
    )
    trajecta_result = json.loads(trajecta_run_path.read_text(encoding="utf-8"))
    if flexpart_result.get("status") != "passed" or trajecta_result.get("status") != "passed":
        raise ComparisonError("scientific comparison requires two passed product runs")
    flexpart_contract = json.loads(
        (flexpart_case / "M5_A5_FLEXPART_CASE.json").read_text(encoding="utf-8")
    )
    trajecta_contract = json.loads(
        (trajecta_run_path.parent / "M5_A5_TRAJECTA_CASE.json").read_text(encoding="utf-8")
    )
    contract_keys = ("time_step_seconds", "output_interval_seconds")
    if any(flexpart_contract.get(key) != trajecta_contract.get(key) for key in contract_keys):
        raise ComparisonError("scientific comparison time contract mismatch")
    output_interval_seconds = int(flexpart_contract["output_interval_seconds"])
    product_files = sorted((flexpart_case / "output").glob("partoutput_*.nc"))
    if len(product_files) != 1:
        raise ComparisonError("FLEXPART product run must contain one particle NetCDF")
    _eccodes, netcdf4, numpy = _stage_modules()
    expected_times = list(
        range(
            START_UNIX + output_interval_seconds,
            END_UNIX + 1,
            output_interval_seconds,
        )
    )
    flexpart_rows: list[dict[str, object]] = []
    with netcdf4.Dataset(product_files[0].as_posix()) as dataset:
        offsets = [int(value) for value in dataset.variables["time"][:]]
        times = [START_UNIX + value for value in offsets]
        if times != expected_times:
            raise ComparisonError(f"FLEXPART product times drifted: {times}")
        particle_count = len(dataset.dimensions["particle"])
        for index, physical_time in enumerate(times):
            longitude = _masked_to_nan(numpy, dataset.variables["lon"][:, index])
            latitude = _masked_to_nan(numpy, dataset.variables["lat"][:, index])
            height = _masked_to_nan(numpy, dataset.variables["z"][:, index])
            topography = _masked_to_nan(numpy, dataset.variables["to"][:, index])
            metrics = _ensemble_metrics(numpy, longitude, latitude, height + topography)
            if metrics["nonfinite_count"] != 0 or metrics["coordinate_count"] != particle_count:
                raise ComparisonError("FLEXPART active/status accounting is ambiguous")
            flexpart_rows.append(
                {
                    "physical_time_unix": physical_time,
                    "active_count": particle_count,
                    "terminated_count": 0,
                    "termination_distribution": {},
                    **metrics,
                }
            )

    trajecta_output = Path(str(trajecta_result["run"]["output_directory"]))
    manifest = json.loads((trajecta_output / "run-manifest.json").read_text(encoding="utf-8"))
    sqlite_path = trajecta_output / manifest.get("sqlite", {}).get(
        "relative_path", "particles.sqlite"
    )
    trajecta_rows: list[dict[str, object]] = []
    with sqlite3.connect(os.fspath(sqlite_path)) as connection:
        particle_count = int(connection.execute("SELECT COUNT(*) FROM particle").fetchone()[0])
        for physical_time in expected_times:
            states = connection.execute(
                "SELECT longitude_degrees, latitude_degrees, height_asl_m, particle_status "
                "FROM particle_state WHERE physical_seconds = ? ORDER BY particle_id",
                (physical_time,),
            ).fetchall()
            active = [row for row in states if row[3] == "alive"]
            metrics = _ensemble_metrics(
                numpy,
                [row[0] for row in active],
                [row[1] for row in active],
                [row[2] for row in active],
            )
            terminations = connection.execute(
                "SELECT classification, reason, COUNT(*) FROM termination "
                "WHERE physical_seconds <= ? GROUP BY classification, reason "
                "ORDER BY classification, reason",
                (physical_time,),
            ).fetchall()
            distribution = {
                f"{classification}:{reason}": int(count)
                for classification, reason, count in terminations
            }
            terminated_count = sum(distribution.values())
            if len(active) + terminated_count != particle_count:
                raise ComparisonError(
                    f"Trajecta lifecycle accounting mismatch at {physical_time}"
                )
            trajecta_rows.append(
                {
                    "physical_time_unix": physical_time,
                    "active_count": len(active),
                    "terminated_count": terminated_count,
                    "termination_distribution": distribution,
                    **metrics,
                }
            )

    cross_rows = []
    for flexpart, trajecta in zip(flexpart_rows, trajecta_rows, strict=True):
        centroid_separation = float(
            _great_circle_distance(
                numpy,
                flexpart["centroid_longitude_degrees"],
                flexpart["centroid_latitude_degrees"],
                trajecta["centroid_longitude_degrees"],
                trajecta["centroid_latitude_degrees"],
            )
        )
        flexpart_dispersion = float(flexpart["rms_horizontal_dispersion_m"])
        flexpart_occupancy = int(flexpart["occupied_audit_cells"])
        cross_rows.append(
            {
                "physical_time_unix": flexpart["physical_time_unix"],
                "horizontal_centroid_separation_m": centroid_separation,
                "vertical_centroid_difference_m": float(
                    trajecta["centroid_height_asl_m"]
                )
                - float(flexpart["centroid_height_asl_m"]),
                "transport_distance_difference_m": float(
                    trajecta["centroid_distance_from_source_m"]
                )
                - float(flexpart["centroid_distance_from_source_m"]),
                "dispersion_width_ratio_trajecta_over_flexpart": (
                    float(trajecta["rms_horizontal_dispersion_m"]) / flexpart_dispersion
                    if flexpart_dispersion > 0
                    else None
                ),
                "occupancy_ratio_trajecta_over_flexpart": (
                    int(trajecta["occupied_audit_cells"]) / flexpart_occupancy
                    if flexpart_occupancy > 0
                    else None
                ),
            }
        )
    value = {
        "schema_version": "trajecta.m5-a5-scientific-comparison/v1",
        "status": "passed",
        "particle_count": particle_count,
        "common_output_times_unix": expected_times,
        "flexpart": flexpart_rows,
        "trajecta": trajecta_rows,
        "cross_model": cross_rows,
        "comparability": {
            "input_source_fields": "exact",
            "encoded_meteorology_values": "aligned",
            "output_instants": "exact",
            "particle_count_and_mass": "exact",
            "longitude_latitude_height_asl": "aligned",
            "ensemble_metrics": "aggregate-only",
            "particle_trajectory_crosswalk": "not-comparable",
            "sqlite_provenance_overhead": "not-comparable",
        },
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    write_json(output, value)
    print(output)
    return 0


def run_flexpart(arguments: argparse.Namespace) -> int:
    case = arguments.case.resolve()
    binary = arguments.binary.resolve()
    manifest_path = case / "M5_A5_FLEXPART_CASE.json"
    result_path = case / "M5_A5_FLEXPART_RUN.json"
    if not binary.is_file():
        raise ComparisonError(f"FLEXPART binary missing: {binary}")
    if not manifest_path.is_file():
        raise ComparisonError(f"prepared case manifest missing: {manifest_path}")
    if result_path.exists():
        raise ComparisonError(f"refusing to overwrite FLEXPART run evidence: {result_path}")
    output = case / "output"
    if not output.is_dir() or any(output.iterdir()):
        raise ComparisonError(f"FLEXPART output directory is absent or nonempty: {output}")

    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if manifest.get("schema_version") != SCHEMA_VERSION:
        raise ComparisonError("prepared FLEXPART case schema identity mismatch")

    environment = os.environ.copy()
    environment.update(
        {
            "OMP_NUM_THREADS": "4",
            "OMP_DYNAMIC": "FALSE",
            "OMP_PROC_BIND": "close",
            "OMP_PLACES": "cores",
        }
    )
    command = [
        "taskset",
        "-c",
        arguments.cpu_set,
        "/usr/bin/time",
        "-v",
        str(binary),
        "pathnames",
    ]
    started = time.monotonic_ns()
    try:
        completed = subprocess.run(
            command,
            cwd=case,
            env=environment,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=arguments.timeout_seconds,
            check=False,
        )
        timed_out = False
    except subprocess.TimeoutExpired as error:
        completed = subprocess.CompletedProcess(
            command,
            124,
            stdout=error.stdout or b"",
            stderr=error.stderr or b"",
        )
        timed_out = True
    wall_nanoseconds = time.monotonic_ns() - started
    stdout_path = case / "flexpart.stdout.log"
    stderr_path = case / "flexpart.stderr.log"
    stdout_path.write_bytes(completed.stdout)
    stderr_path.write_bytes(completed.stderr)

    time_evidence = None
    if not timed_out:
        time_evidence = parse_time_verbose(completed.stderr.decode("utf-8", errors="replace"))
    artifacts = []
    for path in sorted(output.rglob("*")):
        if path.is_file():
            artifacts.append(
                {
                    "path": path.relative_to(case).as_posix(),
                    "size_bytes": path.stat().st_size,
                    "sha256": sha256(path),
                }
            )
    result = {
        "schema_version": "trajecta.m5-a5-flexpart-run/v1",
        "case_manifest_sha256": sha256(manifest_path),
        "binary_sha256": sha256(binary),
        "command": command,
        "environment": {
            key: environment[key]
            for key in ("OMP_NUM_THREADS", "OMP_DYNAMIC", "OMP_PROC_BIND", "OMP_PLACES")
        },
        "cpu_set": arguments.cpu_set,
        "timed_out": timed_out,
        "exit_code": completed.returncode,
        "wall_nanoseconds": wall_nanoseconds,
        "time_verbose": time_evidence,
        "stdout_sha256": sha256(stdout_path),
        "stderr_sha256": sha256(stderr_path),
        "artifacts": artifacts,
        "status": "passed" if completed.returncode == 0 and not timed_out else "failed",
    }
    result_path.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(result_path)
    return 0 if result["status"] == "passed" else 1


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(description=__doc__)
    commands = result.add_subparsers(dest="command", required=True)
    stage_command = commands.add_parser("stage-meteorology")
    stage_command.add_argument("--source", type=Path, required=True)
    stage_command.add_argument("--output", type=Path, required=True)
    stage_command.set_defaults(handler=stage_meteorology)
    audit_command = commands.add_parser("audit-meteorology")
    audit_command.add_argument("--source", type=Path, required=True)
    audit_command.add_argument("--trajecta-data", type=Path, required=True)
    audit_command.add_argument("--meteorology", type=Path, required=True)
    audit_command.add_argument("--output", type=Path, required=True)
    audit_command.set_defaults(handler=audit_meteorology)
    prepare_command = commands.add_parser("prepare-flexpart")
    prepare_command.add_argument("--flexpart-options", type=Path, required=True)
    prepare_command.add_argument("--species-file", type=Path, required=True)
    prepare_command.add_argument("--meteorology", type=Path, required=True)
    prepare_command.add_argument("--output", type=Path, required=True)
    prepare_command.add_argument("--particles", type=int, required=True)
    prepare_command.add_argument("--mode", choices=("core", "product"), required=True)
    prepare_command.add_argument("--time-step-seconds", type=int, default=300)
    prepare_command.add_argument("--output-interval-seconds", type=int, default=600)
    prepare_command.set_defaults(handler=prepare)
    run_command = commands.add_parser("run-flexpart")
    run_command.add_argument("--binary", type=Path, required=True)
    run_command.add_argument("--case", type=Path, required=True)
    run_command.add_argument("--cpu-set", default="0-3")
    run_command.add_argument("--timeout-seconds", type=int, default=1800)
    run_command.set_defaults(handler=run_flexpart)
    trajecta_prepare = commands.add_parser("prepare-trajecta")
    trajecta_prepare.add_argument("--data", type=Path, required=True)
    trajecta_prepare.add_argument("--output", type=Path, required=True)
    trajecta_prepare.add_argument("--particles", type=int, required=True)
    trajecta_prepare.add_argument("--time-step-seconds", type=int, default=300)
    trajecta_prepare.add_argument("--output-interval-seconds", type=int, default=600)
    trajecta_prepare.set_defaults(handler=prepare_trajecta)
    trajecta_run = commands.add_parser("run-trajecta")
    trajecta_run.add_argument("--package-root", type=Path, required=True)
    trajecta_run.add_argument("--case", type=Path, required=True)
    trajecta_run.add_argument("--cpu-set", default="0-3")
    trajecta_run.add_argument("--timeout-seconds", type=int, default=1800)
    trajecta_run.add_argument("--require-performance", action="store_true")
    trajecta_run.set_defaults(handler=run_trajecta)
    science = commands.add_parser("compare-science")
    science.add_argument("--flexpart-case", type=Path, required=True)
    science.add_argument("--trajecta-run", type=Path, required=True)
    science.add_argument("--output", type=Path, required=True)
    science.set_defaults(handler=scientific_comparison)
    return result


def main() -> int:
    arguments = parser().parse_args()
    try:
        return int(arguments.handler(arguments))
    except (ComparisonError, OSError, ValueError) as error:
        print(f"m5-a5 comparison: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
